### ISSUE TITLE
Manga Plus extension does not have label for "Ultra Jump" serialization and does not have fall-back for "blank" serialization

### ISSUE THREAD

**Issue by bargy** [keiyoushi/tachiyomi-extensions-source#6131] opened 2024-11-18 17:08 UTC
### Source information

MANGA Plus by SHUEISHA

### Source language

English/All Languages (likely)

### Steps to reproduce

1. Open "MANGA Plus by SHUEISHA" extension
2. Search for "Bug Ego"
3. The following error message is displayed and the description nor the chapters for the manga are fetched - `eu.kanade.tachiyomi.extension.all.mangaplus.LabelCode does not contain element with name 'UJ' at path $.success.titleDetailView.label.label`

### Expected behavior

The manga description is filled out and the chapters are available to view.

### Actual behavior

The following error is displayed in a toast message:
`Serialization Exception:
eu.kanade.tachiyomi.extension.all.mangaplus.LabelCode does not contain element with name 'UJ' at path $.success.titleDetailView.label.label`
![Screenshot_20241118_180141_Mihon](https://github.com/user-attachments/assets/d5e4a8cd-8885-4598-8c93-105d52dcd6df)

### Mihon/Tachiyomi version

Mihon 0.17.0

### Android version

Android 14

### Other details

Even in webview, the manga "Bug Ego" does not have a serialization label, it appears that the manga has been moving between different magazines (from Weekly Young Jump to Ultra Jump to supposedly Weekly Shonen Jump), so it's likely that this issue could resolve itself if the serialization changes.
I am opening the issue report just in case Manga Plus gets an influx of manga from Ultra Jump and to have a fall-back for a blank serialization label just in case.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-11-18 17:20
Duplicate of #6130

**Closed as not planned by vetleledaal** 2024-11-18 17:20 UTC
Labels: Bug
