### ISSUE TITLE
Can't read any chapter

### ISSUE THREAD

**Issue by xaolanx** [keiyoushi/tachiyomi-extensions-source#4988] opened 2024-09-10 03:28 UTC
### Source information

ReadComicOnline 1.4.26

### Source language

English

### Steps to reproduce

1. Open ReadComicOnline extension
2. Open any comics
3. Open any chapter

### Expected behavior

Images from each chapter should load normally.

### Actual behavior

No images loaded, even though they are there when opening with webview

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-10 03:29
Duplicate of #4115 

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned** 2024-09-10 03:45 UTC
Labels: Bug
