### ISSUE TITLE
Lura toons not working 

### ISSUE THREAD

**Issue by Otakuo00077778** [keiyoushi/tachiyomi-extensions-source#5959] opened 2024-11-08 21:00 UTC
### Source information

Lura too pt.randomscan

### Source language

Português 

### Steps to reproduce

When opening a chapter of the manga it says that it has no pages but in the web view it is working normally ps: you have to pay 7 reais to use. 

### Expected behavior

It should flip the images correctly in the tachiyomi as it appears in the web view 

### Actual behavior

Instead of the images appearing in the chapter, nothing appears 

### Mihon/Tachiyomi version

0.15.3

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-08 21:02
Duplicate of #5739

Search the existing issues first (both open & closed) before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned by Smol-Ame** 2024-11-08 21:02 UTC
Labels: Bug
