### ISSUE TITLE
Goda (Chinese) stopped working

### ISSUE THREAD

**Issue by josephcy95** [keiyoushi/tachiyomi-extensions-source#5388] opened 2024-10-06 10:09 UTC
### Source information

Goda 1.4.31

### Source language

Chinese

### Steps to reproduce

1. Add repo from the website
2. Installed Goda 1.4.31
3. Search for any manga and start reading

### Expected behavior

It should be able to read the manga normally

### Actual behavior

It shows an error "Unexpected JSON token at offset 144...." then return to the manga details page.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

The english version is working though, I've tried different mirrors, cleared cookies, changing network, changing agent

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-06 10:15
Duplicate of #5386

**Closed as not planned** 2024-10-06 11:32 UTC
Labels: Bug

**Comment by ReanSchwarzer9029** [comment] 2024-10-06 13:32
![image](https://github.com/user-attachments/assets/9cfa358d-c5a1-4d79-9b34-a9a4aaf4ebe0)

Dropping screenshot of the error

**Comment by yigedajiaque** [comment] 2024-10-06 17:59
> Duplicate of #5386

tk
