### ISSUE TITLE
Luascans not working

### ISSUE THREAD

**Issue by L1taharu8** [keiyoushi/tachiyomi-extensions-source#6666] opened 2024-12-18 07:04 UTC
### Source information

Lua Scans 1.4.40

### Source language

English

### Steps to reproduce

Checking the scans under latest and not showing the titles

### Expected behavior

Should show the titles under the sources

### Actual behavior

Saying that the website is down when it's not

### Mihon/Tachiyomi version

TachiJ2k 1.74

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-18 07:05
Duplicate of #6631

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-12-18 07:05 UTC
Labels: Bug, Duplicate
