### ISSUE TITLE
Roumanwu updated error

### ISSUE THREAD

**Issue by leession** [keiyoushi/tachiyomi-extensions-source#5448] opened 2024-10-09 08:11 UTC
### Source information

Roumanwu 1.4.10

### Source language

Chinese

### Steps to reproduce

1、Click on the roumanwu plugin. The updates and common browsing contents cannot be displayed normally and are empty.
2、The collection contents of roumanwu cannot be updated normally.

### Expected behavior

1、The updates and common browsing contents of roumanwu can be displayed normally.
2、The collection contents of roumanwu can be updated normally.

### Actual behavior

1、Click on the roumanwu plugin. The updates and common browsing contents cannot be displayed normally and are empty.
2、The collection contents of roumanwu cannot be updated normally.

### Mihon/Tachiyomi version

0.16.X

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-09 08:12
Duplicate of #5374 

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned by Smol-Ame** 2024-10-09 08:12 UTC
Labels: Bug
