### ISSUE TITLE
Lura toon denovo 

### ISSUE THREAD

**Issue by 0nur65** [keiyoushi/tachiyomi-extensions-source#6496] opened 2024-12-06 14:33 UTC
### Source information

Lura tonn 1.4.56

### Source language

Português 

### Steps to reproduce

O WebView está funcionando, as atualizações estão funcionando, mas os capítulos não estão abrindo devido a um erro
![Screenshot_20241206-112623_Mihon](https://github.com/user-attachments/assets/b733d178-3528-4622-b9b3-c1354e28dfcd)

### Expected behavior

O app deveria abrir normalmente e o dowload deveria ocorrer normalmente 

### Actual behavior

Deu erro

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---Adicione um :+1: [reação] a [questões que você acha importantes].[reação]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/[issues você acha importante]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TheKingTermux** [comment] 2024-12-06 14:47
Duplicate of #6468

**Closed as not planned** 2024-12-06 14:53 UTC
Labels: Bug
