### ISSUE TITLE
Vortex Scans no results found

### ISSUE THREAD

**Issue by MrMidnight001** [keiyoushi/tachiyomi-extensions-source#6480] opened 2024-12-05 12:15 UTC
### Source information

Vortex Scans 1.4.40

### Source language

English

### Steps to reproduce

1. Open Vortex Scans
2. No Results found, manhua doesn't shows up
3. Check the Webview and it's fine

### Expected behavior

This should happen... 
![Screenshot_2024-12-05-20-09-28-40_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/3c8e413d-5195-4398-ad94-673207f59333)

### Actual behavior

This happened instead... 
![Screenshot_2024-12-05-20-08-57-65_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/ce8819c2-e145-4aea-b67c-5925ffca04d7)

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-12-05 19:40
Latest tab still works, it's just popular that is broken.

**Comment by mrtear** [comment] 2024-12-06 06:24
Duplicate of #6448

**Closed as not planned** 2024-12-06 07:18 UTC
Labels: Bug, Valid
