### ISSUE TITLE
Asurascans not loading

### ISSUE THREAD

**Issue by Gborrelly** [keiyoushi/tachiyomi-extensions-source#5208] opened 2024-09-24 23:11 UTC
### Source information

Asura scans

### Source language

English 

### Steps to reproduce

Reload asurascans manga

### Expected behavior

Load manga episodes

### Actual behavior

Internal Server Error (NullPointerException)

### Mihon/Tachiyomi version

3.3

### Android version

Ios 18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-09-24 23:13
Duplicate of #5198

**Closed as not planned by vetleledaal** 2024-09-24 23:13 UTC
Labels: Bug
