### ISSUE TITLE
Problema de certificados del servidor en la extensión de manhwas.net

### ISSUE THREAD

**Issue by G22-Delis-Dev** [keiyoushi/tachiyomi-extensions-source#5032] opened 2024-09-13 13:58 UTC
### Source information

Manhwas.net 1.4.11

### Source language

Español

### Steps to reproduce

![Imagen de WhatsApp 2024-09-13 a las 09 51 08_0cef1776](https://github.com/user-attachments/assets/32cb22a8-a98e-4ec4-ae50-423d0333e01d)

### Expected behavior

Cargar el contenido inmediatamente

### Actual behavior

no cargan los manhwas y presenta esto [SSLHandshakeException: Unacceptable certificate: CN=AAA Certificate Services, 0=Comodo CA Limited, L=Salford, ST=Greater Manchester, C=GB]

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-09-13 16:43
Duplicate of #5020

**Closed as not planned** 2024-09-13 16:43 UTC
Labels: Bug
