### ISSUE TITLE
I can't search for anything in hitomi

### ISSUE THREAD

**Issue by KRONOSERA** [keiyoushi/tachiyomi-extensions-source#6795] opened 2024-12-24 18:44 UTC
### Source information

Hitomi 1. 4. 34

### Source language

English

### Steps to reproduce

When i try so search for anything in hitomi
A pop out screen Appear (stream was rest : INTERNAL _error
![Screenshot_2024-12-24-18-42-55-16_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/b4a06cda-5468-49ad-9d6a-3d36da4f0d57)

### Expected behavior

Show a result of what i searched for 

### Actual behavior

stream was rest : INTERNAL _error

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AwkwardPeak7** [comment] 2024-12-25 02:44
Duplicate of #6698

**Comment by AwkwardPeak7** [comment] 2024-12-25 02:44
as a workaround, use less keywords or use filters

**Closed as not planned by AwkwardPeak7** 2024-12-25 02:44 UTC
Labels: Bug, Duplicate
