### ISSUE TITLE
Bato.to pages won't load

### ISSUE THREAD

**Issue by ths1234** [keiyoushi/tachiyomi-extensions-source#848] opened 2024-01-31 10:58 UTC
### Source information

"Bato.to 1.4.34"

### Source language

multi

### Steps to reproduce

1. click on the Bato source
2. Click on a manga/manhua
3. Click on a chapter

### Expected behavior

It should load the pages of the chapter so that you can read them.

### Actual behavior

It emediately exits the chapter and says no pages found.

### Tachiyomi version

Mihon stable 0.16.3

### Android version

"Android 14"

### Other details

It loads the source perfectly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment] 2024-01-31 11:05
Duplicate of #842

**Closed as not planned by SnakeDoc83** 2024-01-31 11:05 UTC
Labels: Bug, Duplicate
