### ISSUE TITLE
Mangatale : NullPointerException when refreshing manga

### ISSUE THREAD

**Issue by Asphyxia444** [keiyoushi/tachiyomi-extensions-source#4990] opened 2024-09-10 06:57 UTC
### Source information

Mangatale 1.4.33

### Source language

Indonesia

### Steps to reproduce

1. Try refresh comics from Mangatale
2. 
![Screenshot_20240910_145450_Mihon](https://github.com/user-attachments/assets/defeb138-3c9c-4e45-aadd-1875b56dd298)

### Expected behavior

Refresh chapters

### Actual behavior

Error

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-10 07:12
Their domain changed, causing this issue, so duplicate of #4986

**Closed as not planned** 2024-09-10 09:14 UTC
Labels: Bug
