### ISSUE TITLE
Http404 extension don't work

### ISSUE THREAD

**Issue by Etsh74** [keiyoushi/tachiyomi-extensions-source#2228] opened 2024-04-01 15:08 UTC
### Source name

Galaxy manga

### Source language

Ar

### Source link

https://flixscans.com

### Other details

![Screenshot_20240401-170503](https://github.com/keiyoushi/extensions-source/assets/163314796/31fe1ba7-a061-4e34-a5f1-e77a790cb229)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-04-01 15:09
Duplicate of #1923

**Closed as not planned** 2024-04-01 15:10 UTC
Labels: Duplicate, Source is down
