### ISSUE TITLE
Bug download kiryuu

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#1747] opened 2024-03-07 14:24 UTC
### Source information

Kiryuu 1.4.36

### Source language

Indonesian (ID)

### Steps to reproduce

1. Download chapter
2. Open chapter
3. Done

### Expected behavior

Can be read normally

### Actual behavior

No pages found, or also only partially open.
It can only be read in full when it has been read online full and then downloaded. If you download it first without reading online, the result is no pages found.
Likewise, if you only read part of it online, the results will also be part when you read it downloaded.

### Mihon/Tachiyomi version

Test on J2k 1.7.4 / SY 1.10.2

### Android version

Android 13

### Other details

More details can be seen in the following video

https://github.com/keiyoushi/extensions-source/assets/157118563/6d3a5f0f-0961-4275-968d-7ecf65b336b2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-08-08 11:32
Duplicate of #3756

**Closed as not planned** 2024-08-08 11:32 UTC
Labels: Bug, Duplicate
