### ISSUE TITLE
VyvyManga changed URL

### ISSUE THREAD

**Issue by Mikokito** [keiyoushi/tachiyomi-extensions-source#5529] opened 2024-10-14 18:08 UTC
### Source information

VyvyManga 1.4.5

### Source language

English

### Source new URL

https://vyvymanga.org

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-14 19:09
Duplicate of #5528

Why did you open three requests about this?

**Closed as not planned by Smol-Ame** 2024-10-14 19:09 UTC
Labels: Bug, Domain changed

**Comment by Mikokito** [comment] 2024-10-14 19:27
Sorry, internet issues, i thought it didn't get through
