### ISSUE TITLE
Manytoon me showing no results found

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#5628] opened 2024-10-21 05:47 UTC
### Source information

Manytoon.me 1.4.41

### Source language

English 

### Steps to reproduce

When opening extension It should show the extension 

### Expected behavior

When opening webview
![Screenshot_2024-10-21-11-16-06-030_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/dea18952-2f82-4a56-903c-29a798f7cff2)

### Actual behavior

No results found 
![Screenshot_2024-10-21-11-15-18-241_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/f6f32248-1cb5-4a4c-b5e0-ec69b60ca562)

### Mihon/Tachiyomi version

Tachiyomi 0.15.3 and tachiyomi sy 1.10.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-21 05:49
Duplicate of #5569 

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't like I told you before

**Closed as not planned by Smol-Ame** 2024-10-21 05:49 UTC
Labels: Bug

**Comment by Achuabdu** [comment] 2024-10-21 05:52
Sry
