### ISSUE TITLE
Covers not loading for most of the titles in hentai2read

### ISSUE THREAD

**Issue by arponroyovi** [keiyoushi/tachiyomi-extensions-source#1863] opened 2024-03-13 23:38 UTC
### Source information

Hentai2Read 1.4.14

### Source language

English

### Steps to reproduce

Only some of the covers are loading and most are not even after refreshing. It seems to show up (not in app) when opened in webview. Tried refreshing the library coversand clearing database, didn't work either.
![Screenshot_20240314-050153_Mihon](https://github.com/keiyoushi/extensions-source/assets/63045686/3075e584-bc05-41d4-955b-34774bd7e2cd)

### Expected behavior

It was fine a few weeks ago

### Actual behavior

Only a select few is showing up
![Screenshot_20240314-052837_Mihon](https://github.com/keiyoushi/extensions-source/assets/63045686/1fc38733-42ce-4ca1-96da-d56262246d25)

### Mihon/Tachiyomi version

Mihon Stable 0.16.4

### Android version

Android 12

### Other details

It's a recent thing. I dont know if its a app side issue but the mihon supports said its best to contact the source/extension maintainer

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-03-14 00:37
Duplicate of #1776

**Closed as not planned by AwkwardPeak7** 2024-03-14 00:37 UTC
Labels: Bug, Duplicate

**Comment by AwkwardPeak7** [comment] 2024-03-14 00:39
@arponroyovi please don't post nsfw screenshots on GitHub
