### ISSUE TITLE
Infernal void scans doesn't load the entire chapter

### ISSUE THREAD

**Issue by potatobong** [keiyoushi/tachiyomi-extensions-source#4916] opened 2024-09-04 12:51 UTC
### Source information

Infernal Void Scans 1.4.38

### Source language

English

### Steps to reproduce

1. Open "Laws of the good child" inside the source
2. Open the first chapter

### Expected behavior

It should load all 42 pages

### Actual behavior

It only loads the first 5 pages

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 13

### Other details

All the other chapters work just fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment] 2024-09-21 19:19
I couldn't reproduce this error. It works fine on my end.

**Comment by choppeh** [comment] 2024-09-21 19:20
Maybe it's a caching problem

**Comment by vetleledaal** [comment] 2024-12-07 21:37
That it only loads the first x pages usually indicates lazy loading on the site, which might be User-Agent specific. I suspect that is the case here, if it's not the cache as previously mentioned.

@potatobong what User-Agent are you using?

**Comment by vetleledaal** [comment] 2024-12-14 22:56
Closing in favor of #6612

**Closed as not planned by vetleledaal** 2024-12-14 22:56 UTC
Labels: Bug
