### ISSUE TITLE
bilibili does not work

### ISSUE THREAD

**Issue by lotuz-afk** [keiyoushi/tachiyomi-extensions-source#5881] opened 2024-11-04 04:27 UTC
### Source information

BILIBILI MANGA 1.4.11

### Source language

chino

### Steps to reproduce

extension does not work
does not load the chapters
in web view it works normally

### Expected behavior

to upload and download the chapi

### Actual behavior

does not load the chapters, and does not let you download them.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-04 07:16
Duplicate of #5827

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you didn't.

**Closed as not planned by Smol-Ame** 2024-11-04 07:16 UTC
Labels: Bug
