### ISSUE TITLE
mangagezgini 

### ISSUE THREAD

**Issue by By-PorfecTo** [keiyoushi/tachiyomi-extensions-source#3204] opened 2024-05-23 19:51 UTC
### Source information

Manga Gezgini 1.4.38

### Source language

Turkish

### Steps to reproduce

When I open the chapter I want to read, it says that the image could not be loaded (I had no problem with the old chapters, this problem is present in the newly uploaded chapters)

### Expected behavior

.

### Actual behavior

.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-05-27 09:19
Duplicate of #3259

**Closed as not planned** 2024-05-27 09:19 UTC
Labels: Bug, Duplicate
