### ISSUE TITLE
Can't load pictures in Happymh(source)

### ISSUE THREAD

**Issue by Nevermind425** [keiyoushi/tachiyomi-extensions-source#1209] opened 2024-02-12 06:53 UTC
### Source information

1.4.7

### Source language

Chinese 

### Steps to reproduce

1.click the comic
2.manga loading
3.load fail
4.But in wedview can load the picture 

### Expected behavior

Load the manga like Norma 

### Actual behavior

Can't load the picture 

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 13

### Other details

https://github.com/keiyoushi/extensions-source/assets/101038505/c06c5654-2c30-4ff6-b611-e8cfbd9fa4fb

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-02-12 12:49
duplicate of #1181

**Closed as not planned by AwkwardPeak7** 2024-02-12 12:49 UTC
Labels: Bug, Duplicate
