### ISSUE TITLE
مشكلة موقع داخل تطبيق

### ISSUE THREAD

**Issue by kirito58** [keiyoushi/tachiyomi-extensions-source#6755] opened 2024-12-22 18:03 UTC
### Source information

1.4.41

### Source language

عريية

### Steps to reproduce

•تدخل موقع من تطبيق يشتغل 
•وقت بحث عن من مانهو تجدها لاكن دائما فصول غير موجود.
•حتى مانهو موجودة في مكتبة لو سويت تحديث لا يجد شيء برغل انه في فصول جدد
![Screenshot_2024-12-22-18-35-35-652_app mihon](https://github.com/user-attachments/assets/ccc65703-5b24-48a8-b423-272622418155)

### Expected behavior

![Screenshot_2024-12-22-19-02-29-641_app mihon](https://github.com/user-attachments/assets/46e9fe33-3b7b-42bf-bc63-68deeb9b0435)

### Actual behavior

![Screenshot_2024-12-22-18-35-35-652_app mihon](https://github.com/user-attachments/assets/f6d6e450-63cd-46bb-9a34-3b0d4d1c17f3)
![Uploading Screenshot_2024-12-22-19-02-35-052_app.mihon.jpg…]()

### Mihon/Tachiyomi version

0.17.1

### Android version

13

### Other details

![Screenshot_2024-12-22-19-02-22-169_app mihon](https://github.com/user-attachments/assets/2861b264-af98-4078-b9dc-2c9f92fbaa9d)
![Screenshot_2024-12-22-19-02-29-641_app mihon](https://github.com/user-attachments/assets/9b562fa9-45d9-42cd-ab99-75a56f047958)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
![Screenshot_2024-12-22-18-35-35-652_app mihon](https://github.com/user-attachments/assets/f3345824-46d1-4370-b0be-f9940e4aad96)
![Screenshot_2024-12-22-19-02-22-169_app mihon](https://github.com/user-attachments/assets/e0aaa637-673b-4a4b-a250-1791800eb683)

**Comment by Smol-Ame** [comment] 2024-12-22 19:15
Duplicate of #5732, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

Also, less spam of screenshots please, for future reference. If it's showing the same issue, two or three is fine.

**Closed as not planned by Smol-Ame** 2024-12-22 19:15 UTC
Labels: Bug, Duplicate

**Comment by Anasplus** [comment] 2024-12-23 02:22
تم رفضك أوتوماتيكيا، لأنك لم ادخل أي معلومات مفيدة
و تلك الصور بدون فائدة
المشكلة بإختصار هي أن موقع "مانجا ليونز" لا يعمل
لكن أصحاب هذا الموقع أجانب لن يفهموا العربية 
و حتى لو كانوا، فأنت لم تلتزم بأضعف 
و أنا لن أعيد البلاغ لأننا لسنا في حاجة لهذا الموقع الذي تستخدمه، فهو يستعمل بوت لسرقة الفصول تلقائيا من موقع مانجا ليك، الذي يسرقها من المواقع المترجمة، جميع الأعمال بدون استثناء موجودة في مواقع أخرى، والأهم هو وجود مواقع أخرى تماما مثل مانجا ليونز، و التي تسرق كذالك من مانجاليك، لذالك إنقل أعمالك لها

**Comment by Smol-Ame** [comment] 2024-12-23 02:41
@Anasplus don't recommend sources. If someone wants a site, they can request it. If there's an extension, people can make issue requests about it, regardless if it's a shit source or not.

I'm using Google Gemini to translate so it's a bit hard to understand, compared to full on translating via Google Translate/browser translate on desktop. Plus, translating always loses/confuses the wording, so I'll reply in English and others can figure it out, especially on GitHub for documentation & for other dual-language contributors to understand.

Contributors can fix and work on whatever sources they want, even with language barriers, but again, up to whoever wants to work on it.
