### ISSUE TITLE
Baozimh.org Not working

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#1383] opened 2024-02-19 01:36 UTC
### Source information

Baozimh.org 1.4.28

### Source language

Chinese

### Steps to reproduce

Doesn't work properly, even when using mirror sites,But it can be accessed normally in webview.
![1](https://github.com/keiyoushi/extensions-source/assets/21278771/5a2eb5bd-b005-4db7-9463-233d3a6fd539)
![2](https://github.com/keiyoushi/extensions-source/assets/21278771/85261273-74e8-4fe3-bdaf-2a6dc4c36abd)

### Expected behavior

Can read manga normally

### Actual behavior

nothing shown

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Other details

The mirror site(**cn.godmanga.com**) has been changed to **cn.godamanga.site**

![QQ截图20240219095947](https://github.com/keiyoushi/extensions-source/assets/21278771/cdc7d72b-3326-4861-8b1e-0d1542d98408)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hsiayuchih** [comment] 2024-02-19 01:44
The mirror site(**cn.godmanga.com**) has been changed to: **cn.godamanga.site**

**Comment by stevenyomi** [comment] 2024-02-19 10:01
Duplicate of #826

**Closed as not planned by stevenyomi** 2024-02-19 10:01 UTC
Labels: Bug, Duplicate
