### ISSUE TITLE
Manwa1.4.5中所有漫画打开均提示“没有图片”

### ISSUE THREAD

**Issue by dqw18cm** [keiyoushi/tachiyomi-extensions-source#5084] opened 2024-09-16 03:54 UTC
### Source information

“Manwa1.4.5”

### Source language

“中文”

### Source new URL

不知道

### Other details

![Screenshot_20240916_115326](https://github.com/user-attachments/assets/4740bd77-84c6-4850-adf1-37a11f7d4ab8)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-16 04:07
Duplicate of #5060

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't. Also, if it wasn't a duplicate, this is the wrong issue request, their domain/baseUrl didn't change.

**Closed as not planned** 2024-09-16 10:31 UTC
Labels: Bug, Domain changed

**Comment by dqw18cm** [comment] 2024-09-16 17:56
The issue has been solved quickly after renewing the extention released yesterday. Thanks, and I am sorry about that I have the problem in the wrong category.
