### ISSUE TITLE
Iqiyi shows HTTP 404

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#1628] opened 2024-03-01 01:40 UTC
### Source information

Iqiyi 1.4.2

### Source language

Chinese

### Steps to reproduce

the extension doesn't work.Browsing with webview reveals that the domain automatically jumps to the https://manhua.iqiyi.com/
![image](https://github.com/keiyoushi/extensions-source/assets/21278771/226be0b0-b395-4f88-94f3-741edc601702)

### Expected behavior

Can read manga normally.

### Actual behavior

http 404

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2024-03-01 09:55
Duplicate of #1474

**Closed as not planned by stevenyomi** 2024-03-01 09:55 UTC
Labels: Bug, Duplicate
