### ISSUE TITLE
Toonkor extension update

### ISSUE THREAD

**Issue by Malvessss** [keiyoushi/tachiyomi-extensions-source#6112] opened 2024-11-18 02:00 UTC
### Source information

Toonkor 1.4.4

### Source language

 Korean - 한국어

### Source new URL

https://toonkor455.com/

### Other details

![Screenshot_20241117-225906_Chrome_Beta](https://github.com/user-attachments/assets/496b5e73-1d49-4a25-92a8-0345fc67f829)
![Screenshot_20241117-225848_Mihon](https://github.com/user-attachments/assets/356026bd-89a4-4eab-8977-2613baf030ba)
![Screenshot_20241117-225137_Mihon](https://github.com/user-attachments/assets/4eb07d99-d48f-4ab6-8a37-de492bf3e2c5)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-11-18 02:10
Duplicate of #227

As mentioned in that issue, you can change the baseURL for the extension (app's Browse Page > Extensions tab > Toonkor settings). Just input the current link, restart the app, and it should work for the time being.

![Screenshot_20241118_100443_Mihon.png](https://github.com/user-attachments/assets/e019e455-4e8a-4e27-bd92-4f9017cf7ec8)

**Closed as not planned by Smol-Ame** 2024-11-18 02:10 UTC
Labels: Bug, Domain changed
