### ISSUE TITLE
Batcave.biz source request

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#5231] opened 2024-09-25 20:32 UTC
### Source name

batcave.biz

### Source link

https://batcave.biz

### Source language

English

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [x] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-25 21:46
Duplicate of #4827 

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned** 2024-09-28 10:53 UTC
Labels: Source request
