### ISSUE TITLE
Tsuki Mangás returning NullPointerException

### ISSUE THREAD

**Issue by AshbornXS** [keiyoushi/tachiyomi-extensions-source#3825] opened 2024-06-30 15:42 UTC
### Source information

Tsuki Mangás 1.4.5

### Source language

Brazilian Portuguese

### Steps to reproduce

1. just open the extension

### Expected behavior

should fetch and return the info

### Actual behavior

returns NullPointerException even though the site is alright

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

opened an issue early this last weak(#3788) but it got auto closed and the issue still persists, hopping this one keeps open to get attention to the issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-06-30 18:48
Duplicate of #2897

**Closed as not planned by vetleledaal** 2024-06-30 18:48 UTC
Labels: Bug, Duplicate
