### ISSUE TITLE
Roumanwu无法使用

### ISSUE THREAD

**Issue by zhangqp210615** [keiyoushi/tachiyomi-extensions-source#5390] opened 2024-10-06 12:54 UTC
### Source information

1.4.10

### Source language

Chinese

### Steps to reproduce

打开roumanwu的漫画

### Expected behavior

无法打开

### Actual behavior

出现字符串  JsonDecodingException:Expected start of the object'{',but had 'EOF' instead at path:$ JSON input:

### Mihon/Tachiyomi version

0.15.3

### Android version

androp11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-06 14:52
Duplicate of #5374

Search the existing issues before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned** 2024-10-06 15:10 UTC
Labels: Bug
