### ISSUE TITLE
Infernal void scane 

### ISSUE THREAD

**Issue by EdgeHRR** [keiyoushi/tachiyomi-extensions-source#6651] opened 2024-12-17 11:00 UTC
### Source information

1.4.40

### Source language

English 

### Steps to reproduce

WebView is working but extension not working.
![Screenshot_2024-12-17-16-51-25-79_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/4ef651ae-782f-431d-8900-0a8cf3163b44)

### Expected behavior

It's should get updated chapters.

### Actual behavior

Should be working. But nothing getting update showing error.
![Screenshot_2024-12-17-16-56-10-89_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/61aaa9ce-a528-4d7b-b823-bffdc151cd91)

### Mihon/Tachiyomi version

Mihon 0.17.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-17 12:30
Duplicate of #6612

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-12-17 12:30 UTC
Labels: Bug, Duplicate
