### ISSUE TITLE
Reset Scans Changed domain

### ISSUE THREAD

**Issue by WolfAlvein** [keiyoushi/tachiyomi-extensions-source#4820] opened 2024-08-29 10:08 UTC
### Source information

Reset Scans 1.4.39

### Source language

English

### Source new URL

https://resetscan.com/

### Other details

The url changed from: https://reset-scans.co/
To: https://resetscan.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-29 17:02
Duplicate of #4794 (for extension-related issue)

Also, no it's not.

![Screenshot_20240829_100129](https://github.com/user-attachments/assets/713d415b-5164-4cc5-88d6-244f20291c32)
![Screenshot_20240829_100151](https://github.com/user-attachments/assets/0adc38d9-2f17-4b07-892b-a1433fb4227d)

**Closed as not planned** 2024-08-30 04:50 UTC
Labels: Bug, Duplicate, Domain changed
