### ISSUE TITLE
Komik-cast.com source request

### ISSUE THREAD

**Issue by Aki249** [keiyoushi/tachiyomi-extensions-source#5262] opened 2024-09-27 07:45 UTC
### Source name

Komik-cast 

### Source link

https://komik-cast.com

### Source language

Indonesia

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-27 07:58
Duplicate of #2822 

Search the existing issues before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned** 2024-09-27 08:09 UTC
Labels: Source request
