### ISSUE TITLE
Genz toons not working 

### ISSUE THREAD

**Issue by AryanMithbawkar** [keiyoushi/tachiyomi-extensions-source#5516] opened 2024-10-13 16:00 UTC
### Source information

1.4.34

### Source language

ENGLISH 

### Steps to reproduce

step 1: open extension 
Step 2: shows no results found 
Step 3: open web view , it shows website fine

### Expected behavior

Should work on extension 

### Actual behavior

No results found shows when entering extension 
![Screenshot_20241013_212522_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/82de4d96-3e55-49fb-a0a9-dee6ea97203d)
![Screenshot_20241013_212526_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/770147f9-75f8-4ace-a311-847c0b5c1c3f)

### Mihon/Tachiyomi version

1.7.4

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-13 19:27
Duplicate of #5445

Search the existing issues before opening a new one, and acknowledging that you did when you clearly didn't (you know that there's a domain change, don't open another request because you can't wait or read.)

**Closed as not planned by Smol-Ame** 2024-10-13 19:27 UTC
Labels: Bug

**Comment by AryanMithbawkar** [comment] 2024-10-13 19:34
But the domain is updated in the extension url which is genzupdates.com but still not working i acknowledge that

**Comment by AryanMithbawkar** [comment] 2024-10-13 19:37
![IMG_20241014_010623](https://github.com/user-attachments/assets/f00e8829-9e5c-4bdd-b80d-293779c0a17a)

**Comment by AryanMithbawkar** [comment] 2024-10-13 19:37
> Duplicate of #5445
> 
> Search the existing issues before opening a new one, and acknowledging that you did when you clearly didn't (you know that there's a domain change, don't open another request because you can't wait or read.)

See above

**Comment by AwkwardPeak7** [comment] 2024-10-13 19:39
it is the webview redirecting, still need to change domain and theme in code

**Comment by AryanMithbawkar** [comment] 2024-10-13 19:41
> it is the webview redirecting, still need to change domain and theme in code

Ok and sorry to disturb
