### ISSUE TITLE
can't access manhwa18

### ISSUE THREAD

**Issue by Key-explanation** [keiyoushi/tachiyomi-extensions-source#6074] opened 2024-11-16 01:30 UTC
### Source information

Manhwa18 1.4.11

### Source language

English

### Steps to reproduce

1. Open a library in manhwa18 
2. Open a chapter 
3. It says 'no pages found'

### Expected behavior

Normally it should show the chapter

### Actual behavior

It says no pages found even though the site works fine in webview

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 11

### Other details

It happened a week ago or so. I can't access manhwa chapters on Mihon, it says 'no pages found' but have no problem access their site using webview.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-11-16 02:30
Duplicate of #5996

**Closed as not planned by vetleledaal** 2024-11-16 02:30 UTC
Labels: Bug
