### ISSUE TITLE
Kappa beast webpage updated

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#5425] opened 2024-10-08 01:12 UTC
### Source information

Kappa beast 1.4.30

### Source language

English 

### Steps to reproduce

Open get error 404

### Expected behavior

Open and see sources

### Actual behavior

The website just updated its page. Maybe it's not sync with the old version of repo?

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-08 01:59
Duplicate of #4885

Don't close your issue to open a new one with the same error to bump it.

**Closed as not planned by Smol-Ame** 2024-10-08 01:59 UTC
Labels: Bug
