### ISSUE TITLE
Slimeread 

### ISSUE THREAD

**Issue by rtz00** [keiyoushi/tachiyomi-extensions-source#6753] opened 2024-12-22 15:53 UTC
### Source information

Slimeread

### Source language

Português (Brazil)

### Steps to reproduce

Erro api

### Expected behavior

Abrir normalmente eu acho

### Actual behavior

Fica dando erro

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 13

### Other details

![Screenshot_2024-12-22-12-52-02-403_com discord](https://github.com/user-attachments/assets/5b9cf5a2-15a8-4641-8133-144591392d62)
![Screenshot_2024-12-22-12-52-09-097_com discord](https://github.com/user-attachments/assets/84d45774-3c69-4a3d-8a32-849d177b01a3)
![Screenshot_2024-12-22-12-52-20-227_com discord](https://github.com/user-attachments/assets/4dd34d2c-de1f-43f5-818e-a53b98d4765d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-22 15:56
Duplicate of #6673, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-12-22 15:56 UTC
Labels: Bug, Duplicate

**Comment by rtz00** [comment] 2024-12-22 16:09
> Duplicado de #6673 , já foi relatado antes. Resolva os problemas existentes antes de abrir um novo, e reconheça que você fez isso quando claramente não fez.

Vc sabe uma VPN para usar? Para q o site volte a pega ou sla

**Comment by Smol-Ame** [comment] 2024-12-22 16:25
That's not how that works. The site changed things in their code, which breaks the extensions. The extension itself needs someone to contribute a fix to get it working again.

Wait, migrate to a different source, read in your browser, contribute a fix, or find somewhere else that'll fix it on demand for you.
