### ISSUE TITLE
Msy publisher is not there

### ISSUE THREAD

**Issue by Daffycoast** [keiyoushi/tachiyomi-extensions-source#5329] opened 2024-10-01 14:38 UTC
### Source name

Msy publisher 

### Source link

https://msypublisher.com

### Source language

English

### Acknowledgements

- [ ] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [ ] I have written a meaningful title with the source name.
- [x] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-01 14:42
Duplicate of #5143

Search the existing issues before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned** 2024-10-01 14:44 UTC
Labels: Source request
