### ISSUE TITLE
NineAnime malfunction 

### ISSUE THREAD

**Issue by Code0016** [keiyoushi/tachiyomi-extensions-source#5141] opened 2024-09-20 18:34 UTC
### Source information

NineAnime 1.4 4

### Source language

English 

### Steps to reproduce

1.select nineanime source
2.pick any manga title 
3. Tap to read
4. It will kick out and appear some error 

### Expected behavior

It should can be read without any problem 

### Actual behavior

It kickout from reading mode 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-20 18:38
Isn't this just a duplicate of your own issue #5104

**Comment by Code0016** [comment] 2024-09-20 19:08
I'm sorry i thought it was deleted how to delete this ?

**Closed as completed** 2024-09-20 19:10 UTC
Labels: Bug
