### ISSUE TITLE
Dead source report

### ISSUE THREAD

**Issue by VtxMarques34** [keiyoushi/tachiyomi-extensions-source#6568] opened 2024-12-11 03:25 UTC
### Source name

Lura Toon 1.4.56

### Source language

Português 

### Source link

https://luratoons.net/

### Other details

The links to the works are not going to your home page, thus making it impossible to read the work, for example:

Normal Work Link = https://luratoons.net/quebra-vento/

Work Link on Aniyomi = https://luratoons.net/api/obra/quebra-vento/

The link that opens in the application makes it impossible to read the works, even if we are logged in to the respective website.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-11 04:26
1. It's not a "Source is down" / "Dead source" issue if the site still works, it's only dead if shit toons decided to delete their website & not open a new site.
2. Duplicate of #6468, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-12-11 04:26 UTC
Labels: Source is down
