### ISSUE TITLE
MangSwat: url change

### ISSUE THREAD

**Issue by Etsh72** [keiyoushi/tachiyomi-extensions-source#4045] opened 2024-07-16 12:39 UTC
### Source name

MangSwat

### Source language

Arabic

### Source link

https://swatoon.com/

### Other details

Please fix this extension 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-07-19 05:46
Duplicate of #4099

**Closed as not planned** 2024-07-19 05:46 UTC
Labels: Bug, Duplicate, Domain changed
