### ISSUE TITLE
Add MangaHoNa

### ISSUE THREAD

**Issue by MangaHoNa** [keiyoushi/tachiyomi-extensions-source#2637] opened 2024-04-28 10:44 UTC
### Source name

MangaHoNa

### Source link

https://MangaHoNa.pl

### Source language

Polish

### Other details

icons: 
with background:
![Skonczone_logo_Manga_Ho_NA_to](https://github.com/keiyoushi/extensions-source/assets/161210560/0f9be61c-45ba-489a-baef-e28eabb444bf)
without background: 
![Skonczone_logo_Manga_Ho_NA](https://github.com/keiyoushi/extensions-source/assets/161210560/813ea75d-cc3e-4cd6-8602-5a963adaafcc)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-04-28 10:48
Duplicate of #2635

**Closed as not planned** 2024-04-28 10:48 UTC
Labels: Duplicate, Source request
