### ISSUE TITLE
Infernal Void Scans New URL for Webtoon

### ISSUE THREAD

**Issue by felthand** [keiyoushi/tachiyomi-extensions-source#6647] opened 2024-12-17 06:14 UTC
### Source information

Infernal Void Scans 1.4.40

### Source language

English

### Steps to reproduce

1. Open Infernal Void Scans Webtoon, e.g. 'Rust'
2. Refresh Webtoon
3. See 'No Chapters found' error
4. Click Web View in Webtoon Page
5. Redirected to Vortex Scans Homepage instead of Webtoon Page

### Expected behavior

1. Find New Chapters on Refresh
2. Redirected to Webtoon page on selecting Web view
3. URL is https://hivetoon.com/manga/rust 

### Actual behavior

1. No New Chapters on Refresh
2. Redirected to homepage on selecting Web view
3. Webtoon URL for Vortex has change from "https://hivetoon.com/manga/rust" to "https://hivetoon.com/series/rust" but not yet handled

### Mihon/Tachiyomi version

0.17.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-17 12:30
Duplicate of #6612

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-12-17 12:30 UTC
Labels: Bug, Duplicate

**Comment by felthand** [comment] 2024-12-17 13:57
> Duplicate of #6612
> 
> It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

Apologies, I was under the belief that this was a separate issue
