### ISSUE TITLE
Mangaoni

### ISSUE THREAD

**Issue by Paswors** [keiyoushi/tachiyomi-extensions-source#5144] opened 2024-09-21 04:56 UTC
### Source information

1.4.16

### Source language

Español

### Steps to reproduce

1_No me deja entrar ala extensión 
2_Me sale No se ha podido acceder a Unable to resolve host "manga-oni.com": No address associated with hostname

### Expected behavior

Debería acceder a la extensión y entrar a mis mangas descargados 

### Actual behavior

Me sale
No se ha podido acceder a Unable to resolve host "manga-oni.com": No address associated with hostname 

### Mihon/Tachiyomi version

0.16.5

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Paswors** [comment] 2024-09-21 04:57
Help plz

**Comment by Paswors** [comment] 2024-09-21 04:57
Quiero que me ayuden con la extensión

**Comment by Paswors** [comment] 2024-09-21 04:58
Ya nos e que hacer

**Comment by Paswors** [comment] 2024-09-21 04:59
Dd

**Comment by Smol-Ame** [comment] 2024-09-21 05:07
You've made your issue, no need to comment for help/mess with the issue request afterwards, you're spamming the Keiyoushi Discord GitHub channel. For future reference, make issue request & wait for a response, or come to the Keiyoushi Discord repo-support channel for questions/issues.

As for the issue you're experiencing:
* If you are unable to access/view MangaOni's site, then it's a personal internet issue. Switch networks (mobile data to WiFi, vice-versa), use a VPN, and/check your internet/ad-block/VPN settings to see if it's blocking the site.
* Otherwise, make sure you pass Cloudflare verification in WebView for MangaOni. Either click the help with Cloudflare button at the top of the WebView, or visit this page: https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare

Extension works on my end

**Comment by Paswors** [comment] 2024-09-21 05:24
It doesn't let me enter the webview and when I type webviewn I get page not found And I go to Google and it comes in

**Comment by Smol-Ame** [comment] 2024-09-21 05:30
Just for clarification, WebView is a basic browser that the app/extension uses for Cloudflare & troubleshooting. You can access WebView in your app by clicking either spots (where the green arrows are pointing to in my first screenshot).

But I think the issue is that you have DNS over HTTPS enabled in Mihon Settings > Advanced. Change it or turn it off, then restart the app, and see if you can access it afterwards. If you see Cloudflare in WebView, see my earlier message or the second screenshot in this message.

![Screenshot_20240920_222616_Mihon.png](https://github.com/user-attachments/assets/9e7bcc59-54d9-47cd-9ac1-0adc13d189fe)

![Screenshot_20240920_222649_Mihon.png](https://github.com/user-attachments/assets/7c7efba4-3a1e-4a42-9d4b-d6d7d9fc6188)

**Comment by bapeey** [comment] 2024-09-21 05:34
Intenta activar el DNS sobre HTTP (DoH) en los ajustes de la app o usar un VPN; como ya te dijeron, esto es problema de tu conexión. Recuerda reiniciar la app luego de activar el DoH

**Comment by vetleledaal** [comment] 2024-09-21 18:13
Since the site is working through Google (Chrome?) the issue is as @bapeey mentioned, with DoH. Chrome enables DoH by default which is why it works in your browser and not the extension.

Since this is not an extension issue I'll be closing the issue.

**Closed as not planned by vetleledaal** 2024-09-21 18:13 UTC
Labels: Bug
