### ISSUE TITLE
404 error when trying to use InfinityScans

### ISSUE THREAD

**Issue by MonkeyWarlock** [keiyoushi/tachiyomi-extensions-source#5949] opened 2024-11-08 09:20 UTC
### Source information

InfinityScans 1.4.4

### Source language

English

### Steps to reproduce

Open app
Try to use InfinityScans

### Expected behavior

All comics showing properly 

### Actual behavior

HTTP 404, check website in WebView

### Mihon/Tachiyomi version

Mihon 0.17.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-08 09:49
Duplicate of #5561

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you didn't.

**Closed as not planned** 2024-11-08 09:49 UTC
Labels: Bug
