### ISSUE TITLE
Update site Manga Demon

### ISSUE THREAD

**Issue by DarkDrake009** [keiyoushi/tachiyomi-extensions-source#4798] opened 2024-08-27 17:36 UTC
### Source information

Manga Demon 1.4.12

### Source language

English 

### Steps to reproduce

The domain name is changed to demonicscans.org

### Expected behavior

It's not connecting to the changed domain name

### Actual behavior

It's showing no results

### Mihon/Tachiyomi version

0.16.4.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-27 17:37
Duplicate of #4770 

Search the existing issues before opening a new one, and acknowledging that you did when you clearly didn't

**Closed as not planned** 2024-08-27 17:44 UTC
Labels: Bug, Duplicate
