### ISSUE TITLE
Myreadingmanga stopped working 

### ISSUE THREAD

**Issue by xdeiimoss** [keiyoushi/tachiyomi-extensions-source#5680] opened 2024-10-24 15:09 UTC
### Source name

MyReadingManga 1.4.53

### Source language

Multi

### Describe your suggested feature

Can't access MyReadingManga 
It gives a not found message

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-24 17:19
Duplicate of #5675

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned by Smol-Ame** 2024-10-24 17:19 UTC
Labels: Feature request
