### ISSUE TITLE
Chapters not updating in Arabs Hentai

### ISSUE THREAD

**Issue by tayani1989** [keiyoushi/tachiyomi-extensions-source#5825] opened 2024-11-01 18:09 UTC
### Source information

Arabs Hentai 1.4.2

### Source language

Arabic 

### Steps to reproduce

1. open Arabs Hentai source and I try updating but no new chapters
2. I open source in webview and the same no new chapters
3. But when I open source in browser the new chapters appear.

### Expected behavior

When I update the manhwa on Arabs Hentai source it must updating

### Actual behavior

But the new chapters not updating just in this source, another source working good.

### Mihon/Tachiyomi version

Mihon/tachiyomi and aniyomi

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-12-26 21:04
Duplicate of #3925

**Closed as not planned by vetleledaal** 2024-12-26 21:04 UTC
Labels: Bug, Duplicate
