### ISSUE TITLE
No found page

### ISSUE THREAD

**Issue by X2ZANDER** [keiyoushi/tachiyomi-extensions-source#5754] opened 2024-10-29 08:08 UTC
### Source information

E-hentai

### Source language

All

### Steps to reproduce

When I open an manga , no page found

### Expected behavior

When open a manga or comic, you can read it 

### Actual behavior

When I open a manga, it loading and back to the cover of the manga and say no page found , all the manga in this e-hentai cant be open and says no page found but when I go to webview it work like normal

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-29 08:09
Duplicate of #5745

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-10-29 08:09 UTC
Labels: Bug
