### ISSUE TITLE
MangaReader SocketTimeoutException error

### ISSUE THREAD

**Issue by MaeCher09** [keiyoushi/tachiyomi-extensions-source#6833] opened 2024-12-27 09:54 UTC
### Source information

MangaReader 1.4.6

### Source language

English

### Steps to reproduce

1. Opening the manga page. Keeps loading and the cover image suddenly gone
2. Open the source and still keeps loading.
3. Open it in webview, it's also the same.
4. Open it in browser (chrome), it loads well
5. Tried to change dns thinking it's the problem and agent string but no avail.

### Expected behavior

Should load and routed to the source 

### Actual behavior

Keeps on loading. After load stops, there stated 'SocketTimeoutException'.

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0 and Mihon 0.17.1

### Android version

Android 13

### Other details

I'm not too techy but I still can comprehend all the troubleshooting guide in the official site of tachi and mihon. This is the different version of the source.

Below are the reference images of the issue. Hope that could help.
![Screenshot_2024-12-27-17-32-50-575_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/e11d8733-f338-475a-9c4d-138907540259)
![Screenshot_2024-12-27-17-32-56-906_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/f88c8a40-6edd-4094-ab64-f00f8f7b29e3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-27 09:55
That's a personal internet-related issue: https://mihon.app/docs/guides/troubleshooting/common-issues#unable-to-resolve-host-connection-failed-failed-to-connect-to-timeout-connection-reset

Otherwise, duplicate of #6623

**Closed as not planned by Smol-Ame** 2024-12-27 09:55 UTC
Labels: Bug

**Comment by MaeCher09** [comment] 2024-12-27 10:03
You think so? I already tried to open it in browsers, chrome and brave and it work really well. Only tachiyomi-mihon and forks can't open the source. I also tried to change the dns, even disabled it and even follow the troubleshooting. Nothing happened. 😭
Is there still a way, or do I need to migrate.. 🥺
I'm not techy btw but I can still follow instructions.. ☺️

**Comment by Smol-Ame** [comment] 2024-12-27 10:09
Yes. Also, reminder to restart the app after changing your DNS over HTTPS setting. For any other basic troubleshooting/issues, come to the Keiyoushi Discord repo-support channel for more help. Otherwise, as mentioned, the extension is currently broken.

![Screenshot_20241227_020705_Mihon.png](https://github.com/user-attachments/assets/b18a7e68-6d1c-4361-bdc6-7b86bf2be663)
