### ISSUE TITLE
Asura Scan NullPointerException Error 

### ISSUE THREAD

**Issue by Waxter-Ak** [keiyoushi/tachiyomi-extensions-source#5221] opened 2024-09-25 09:21 UTC
### Source information

Asura Scan 

### Source language

English 

### Steps to reproduce

1 Open Asura Scan Extension 
2 Select a manhwa 
3 Reload it to show new Chapters

### Expected behavior

When Updating the manhwa the new Chapter should show up or if there is no new chapter it will remain as it is.

### Actual behavior

Instead a pop up message shows up and display NullPointerException: NULL 

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-25 09:21
Duplicate of #5198

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't

**Closed as not planned** 2024-09-25 09:44 UTC
Labels: Bug
