### ISSUE TITLE
Ichiromanga ext

### ISSUE THREAD

**Issue by ShoujoLover** [keiyoushi/tachiyomi-extensions-source#4985] opened 2024-09-10 02:16 UTC
### Source name

Ichiromanga

### Source link

https://ichiromanga.my.id/

### Source language

Indonesia

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-10 02:30
Duplicate of self-closed #3852

Don't close existing issues just to open a new one to bump it up

**Comment by TheKingTermux** [comment] 2024-09-10 02:48
Uses MangaThemesia theme

**Closed as not planned** 2024-09-10 03:44 UTC
Labels: Source request
