### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by Outer598** [keiyoushi/tachiyomi-extensions-source#5217] opened 2024-09-25 06:34 UTC
### Source information

Asura scans

### Source language

English 

### Steps to reproduce

When trying to manual update a manhwa within its extension it trows a null pointer exception 

### Expected behavior

It should update

### Actual behavior

Throws a null pointer eception

### Mihon/Tachiyomi version

1.4.39

### Android version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) Android version: 14 (SDK 34; build UP1A.231005.007.A155FXXU3BXG4) Device brand: samsung Device manufacturer: samsung Device name: a15 (a15nsxx) Device model: SM-A155F WebView: Android System WebView 128.0.6613.146

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-25 06:35
Duplicate of #5198 

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't again

**Closed as not planned** 2024-09-25 06:55 UTC
Labels: Bug
