### ISSUE TITLE
Mangaraw have problem!

### ISSUE THREAD

**Issue by devil6venom** [keiyoushi/tachiyomi-extensions-source#1077] opened 2024-02-07 04:55 UTC
### Source information

Mangaraw v1.4.7

### Source language

Japanese 

### Steps to reproduce

1. INSTALL IT
2. Open it,
3. No mangas!!
4. Go to settings and override option,
5. Manga1001.in is active in WebView but in ext,
6. No result found!

### Expected behavior

Should open the site and can be able to browse mangas!

### Actual behavior

No result found!

### Mihon/Tachiyomi version

1.10.2 SY 

### Android version

Android 13

### Other details

Well, website is up but extension have issues!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2024-02-07 09:11
Duplicate of #80

**Closed as not planned** 2024-02-07 09:11 UTC
Labels: Bug, Duplicate
