### ISSUE TITLE
[TheBlank] WebView Results In An Error Screen And The Message "Site Removed"

### ISSUE THREAD

**Issue by SodiumPoisoning** [keiyoushi/tachiyomi-extensions-source#6767] opened 2024-12-23 07:13 UTC
### Source information

The Blank Scanlation

### Source language

English

### Steps to reproduce

1. Click on Source.
2. Click hamburger menu (either three lines or three dots).
3. Click Open in WebView.

### Expected behavior

I should be able to see the website in WebView allowing me to log in and have access to premium content (early access to chapters).

### Actual behavior

![Screenshot_20241223-020145](https://github.com/user-attachments/assets/ae37b8fc-00fb-48c5-a42d-0eead4be6ca8)
I am met with the "Site Removed" screen and am unable to bypass it.

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-23 07:13
Duplicate of #6648, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Comment by Smol-Ame** [comment] 2024-12-23 07:14
Wait you even commented in there, don't make another issue request when you know there's already one

**Closed as not planned by Smol-Ame** 2024-12-23 07:13 UTC
Labels: Bug, Duplicate
