### ISSUE TITLE
Baozimh.org 1.4.28 Display "没有结果（No Results）"

### ISSUE THREAD

**Issue by Qing-Novel** [keiyoushi/tachiyomi-extensions-source#903] opened 2024-02-02 03:58 UTC
### Source information

Baozimh.org 1.4.28

### Source language

chinese

### Steps to reproduce

This source cannot be used, even if the mirror website is switched, it cannot be used, but both mirror websites are also opened in webview
![Screenshot_20240202_113755_app mihon](https://github.com/keiyoushi/extensions-source/assets/136884931/0e8d96a0-2cb3-477e-869f-1d5c43b9c41b)
(
![Screenshot_20240202_114057_app mihon](https://github.com/keiyoushi/extensions-source/assets/136884931/f1d52af1-5a80-4b00-a356-a5ee10fed755)
![Screenshot_20240202_114114_app mihon](https://github.com/keiyoushi/extensions-source/assets/136884931/b0c7c0d7-c8da-46a0-810c-e2d9f3654ef9)
)

### Expected behavior

Should be able to use it normally and see comics

### Actual behavior

Display "没有结果（No Results）
![Screenshot_20240202_113800_app mihon](https://github.com/keiyoushi/extensions-source/assets/136884931/4ccbd1d9-7443-4208-98a5-88bf236fbbfd)
"

### Mihon/Tachiyomi version

mihon 0.16.3

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2024-02-02 04:37
Duplicate of #826

**Closed as not planned by stevenyomi** 2024-02-02 04:37 UTC
Labels: Bug, Duplicate
