### ISSUE TITLE
Mangasail source not working

### ISSUE THREAD

**Issue by Zenbast** [keiyoushi/tachiyomi-extensions-source#1870] opened 2024-03-14 08:15 UTC
### Source information

Mangasail 1.4.5

### Source language

English

### Steps to reproduce

1. Use the search engine for a manga 
2. Error message on the source
![Screenshot_20240314-090553_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/25988157/6ef65de7-0ea0-485b-a815-93f6512c857f)

### Expected behavior

Should show the manga and let us read it like for others sources.

### Actual behavior

Error message.

### Mihon/Tachiyomi version

App version: 1.10.5 (standard, 6c563d7, 65, 2024-03-02T20:42Z)

### Android version

Android version: 10 (SDK 29; build QP1A.190711.020.G965FXXUHFVG4)

### Other details

Device brand: samsung
Device manufacturer: samsung
Device model: SM-G965F
WebView: Android System WebView 81.0.4044.138

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-05-09 21:50
Duplicate of #1673

**Closed as not planned by vetleledaal** 2024-05-09 21:50 UTC
Labels: Bug, Duplicate
