### ISSUE TITLE
Manga Demon extension does not work

### ISSUE THREAD

**Issue by notblured** [keiyoushi/tachiyomi-extensions-source#4839] opened 2024-08-30 01:43 UTC
### Source information

Manga Demon 1.4.12

### Source language

English

### Steps to reproduce

1. Open Manga Demon Extension
2. No contents shown

### Expected behavior

The contents of the source should be shown.

### Actual behavior

"No results found" but webview does work.

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-30 01:44
Duplicate of #4770

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't

**Closed as completed** 2024-08-30 01:45 UTC
Labels: Bug, Duplicate
