### ISSUE TITLE
Asura Scans

### ISSUE THREAD

**Issue by HubikaAd** [keiyoushi/tachiyomi-extensions-source#4183] opened 2024-07-23 15:37 UTC
### Source information

Asura Scans

### Source language

English

### Steps to reproduce

Issue: Not showing any comics since they change the ui of their website, and probably also the url. So, can you please update it. Thank you so much

### Expected behavior

Supposedly showing some comics

### Actual behavior

Not Showing anything
![Screenshot_20240723_233515_app mihon](https://github.com/user-attachments/assets/1059145b-62d5-41f0-87f9-d84b5f8818ab)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-07-23 15:42
Duplicate of #4167

**Closed as not planned by vetleledaal** 2024-07-23 15:42 UTC
Labels: Bug, Duplicate
