### ISSUE TITLE
HentaiFox source runs and shows new titles but has issue loading pages

### ISSUE THREAD

**Issue by Devil360559** [keiyoushi/tachiyomi-extensions-source#5940] opened 2024-11-07 23:22 UTC
### Source information

HentaiFox 

### Source language

English

### Steps to reproduce

Open any title which is not downloaded.
Open the chapter.

### Expected behavior

The chapter is supposed to load properly without any error.

### Actual behavior

The chapter is supposed to load properly, but either it doesn't load or just loads the first page (only sometimes) of the title.
[Removed NSFW image]
![Screenshot_20241108-044708_TachiyomiSY](https://github.com/user-attachments/assets/21e7bd10-ec32-4eae-a2dc-ed91b073d10c)
![Screenshot_20241108-044714_TachiyomiSY](https://github.com/user-attachments/assets/325610ac-8aac-4148-85b0-c03ea1ccd176)

As you can see, it works perfectly fine in Web View
Warning: Picture of site below!

[Removed NSFW image]

### Mihon/Tachiyomi version

TachiyomiSY App version: 1.11.0 Preview build: 573

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Devil360559** [comment] 2024-11-07 23:26
Apologies, it is my first time using this big reporting. I didn't see any extra rules related to bug reporting other than the Acknowledgements at the end of the form. So if I have done any wrong pls correct me.

**Comment by vetleledaal** [comment] 2024-11-07 23:39
Don't post NSFW content on GitHub. I have removed those images from your post.

**Comment by Devil360559** [comment] 2024-11-07 23:40
Okay, thanks for letting me know

**Comment by Smol-Ame** [comment] 2024-11-07 23:57
Duplicate of #5915

**Closed as not planned by Smol-Ame** 2024-11-07 23:57 UTC
Labels: Bug
