### ISSUE TITLE
Asura scan null pointer 

### ISSUE THREAD

**Issue by Gamermemer** [keiyoushi/tachiyomi-extensions-source#5219] opened 2024-09-25 08:30 UTC
### Source information

Asura Scan

### Source language

English

### Steps to reproduce

1.) Open app
2.) Open asura scan
3.) Open comic 
4.) Refresh 
5.)null pointer

### Expected behavior

1.) Open app
2.) Open asura scan
3.) Open comic 
4.) Refresh 
5.)new chapter come

### Actual behavior

It is showing error nul pointer

### Mihon/Tachiyomi version

Tachiyomi stable0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-25 08:31
Duplicate of #5198 

Search the existing issues before opening a new one, and acknowledging that you did when you clearly didn't

**Closed as not planned** 2024-09-25 09:06 UTC
Labels: Bug
