### ISSUE TITLE
[URL Change] KomikindoID 

### ISSUE THREAD

**Issue by clyezen** [keiyoushi/tachiyomi-extensions-source#5191] opened 2024-09-24 01:38 UTC
### Source information

KomikIndoID 1.4.13

### Source language

Indonesian

### Source new URL

https://komikindo.lol/

### Other details

The Url Change from https://komikindo.id/ to https://komikindo.lol/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ringosham** [comment] 2024-09-24 15:46
~~Duplicate of #5167~~

**Comment by Smol-Ame** [comment] 2024-09-24 17:39
@ringosham I don't think it's a duplicate, there's more than one Komikindo (and the one mentioned here, name & version, lines up)

![Screenshot_20240924_103649_Mihon.png](https://github.com/user-attachments/assets/b2ebafcf-8881-449f-875d-fdb095b27e88)

**Comment by ringosham** [comment] 2024-09-24 18:29
Oh yeah. I misread the letters and thought they were the same. Oops.

**Comment by vivalafreak1** [comment] 2024-09-25 06:13
I checked the extension, but in this code appear to be komikindo.tv not komikindo.id to be previous url

**Comment by Smol-Ame** [comment] 2024-09-25 06:14
Mistype on the issue request, but new link is what matters. I always check the old site/extension itself to double-check the link is actually correct

**Closed as completed** 2024-09-25 13:57 UTC
Labels: Bug, Domain changed
