### ISSUE TITLE
It is not possible to read or download any manhwa from the lura toon source.

### ISSUE THREAD

**Issue by Werique69** [keiyoushi/tachiyomi-extensions-source#6484] opened 2024-12-05 15:18 UTC
### Source information

Lura toon 1.4.56

### Source language

Português PT-BR

### Steps to reproduce

https://github.com/user-attachments/assets/fa8bcc88-83cb-4232-9c5f-b56649654a43

### Expected behavior

https://github.com/user-attachments/assets/bb9cf943-4d40-4416-8b97-8bf4eae42432

### Actual behavior

The manhwa no longer opens, it gives an error with the name http error 404

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-05 15:30
Duplicate of #6468

**Closed as not planned by Smol-Ame** 2024-12-05 15:30 UTC
Labels: Bug
