### ISSUE TITLE
ReadComicOnline does not work anymore

### ISSUE THREAD

**Issue by Teosas** [keiyoushi/tachiyomi-extensions-source#4838] opened 2024-08-29 21:49 UTC
### Source information

ReadComicOnline

### Source language

English

### Steps to reproduce

1.open the comic
2.read "solve captcha in webview"
3.open the webview and solve the captcha
4.come back to the "normal reading" view
5.the "solve captcha in webview" text remains

### Expected behavior

1.open the comic
2.read "solve captcha in webview"
3.open the webview and solve the captcha
4.come back to the "normal reading" view
5. refresh and read the comic

### Actual behavior

1.open the comic
2.read "solve captcha in webview"
3.open the webview and solve the captcha
4.come back to the "normal reading" view
5.the "solve captcha in webview" text remains

### Mihon/Tachiyomi version

tachimanga 3.3 and 3.4 (beta)

### Android version

iOS 17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-29 21:55
Duplicate of #4115

Search the existing issues (both open & closed) before opening a new one, and acknowledging that you did when you clearly didn't.

**Comment by Teosas** [comment] 2024-08-29 22:02
I read #4115, and I think the issue is not exactly the same, the message is different and the source was working when that "issue" was opened, I think the issues seems similar, but they are not correlated, often RCO has had cloudflare/captcha problems, but they may not be necessarily correlated with each other

**Comment by Smol-Ame** [comment] 2024-08-29 22:05
It's the same, the issue you're experiencing doesn't matter when the extension is broken from source intentionally breaking it.

You can pass CAPTCHA verification if you go to the extension's settings, and set it to Server 2. But afterwards, while the entries will load & you can "access" the chapters, the comic pages won't load & will just result in #4115

**Comment by Teosas** [comment] 2024-08-29 22:09
Just tried, you are right, i thought they were different problems because of the different messages etc. sorry for wasting time i was just tryna add infos

**Closed as not planned** 2024-08-30 04:45 UTC
Labels: Bug, Duplicate
