### ISSUE TITLE
The URL of the site to change 

### ISSUE THREAD

**Issue by anjaragermai** [keiyoushi/tachiyomi-extensions-source#4304] opened 2024-07-28 05:59 UTC
### Source information

Scan-Manga 1.4.7

### Source language

French 

### Source new URL

https://m.scan-manga.com

### Other details

There are no other details other than the site link to change 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-07-28 13:56
~~The linked URL errors out with a HTTP 404 error.~~

Duplicate of #2232

**Closed as not planned** 2024-07-28 14:00 UTC
Labels: Bug, Domain changed
