### ISSUE TITLE
all Re yume web bugs

### ISSUE THREAD

**Issue by LuxpolCastor** [keiyoushi/tachiyomi-extensions-source#6590] opened 2024-12-12 12:48 UTC
### Source information

re-yume.my.id version 1.4.36

### Source language

Indonesia

### Steps to reproduce

`re` yume has an error, 
1. can't see the latest chapter,
2. all comic covers are blank
3. and all chapters are blank
![Screenshot_20241212-185236](https://github.com/user-attachments/assets/5abdc043-1c30-45fb-9f34-07d15f197a0a)
![Screenshot_20241212-185257](https://github.com/user-attachments/assets/61f32dbd-624f-49ae-a8e7-64f53972103e)
![Screenshot_20241212-185249](https://github.com/user-attachments/assets/3f0182de-6390-4fbd-ba89-9f7cb596e83d)

### Expected behavior

I should be able to see the comic

### Actual behavior

but instead it all gave errors until the chapter was blank

### Mihon/Tachiyomi version

0.17.1

### Android version

android 11

### Other details

1. I can see as usual in web view mode
![Screenshot_20241212-191500](https://github.com/user-attachments/assets/3ac33fb4-6b51-42dd-afd3-8d274a6f9c25)

2. and I don't need to go through cloudflare to access the website

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-12-13 19:28
Duplicate of #4984

**Closed as not planned by vetleledaal** 2024-12-13 19:28 UTC
Labels: Bug, Duplicate
