### ISSUE TITLE
New Domain: Shinigami

### ISSUE THREAD

**Issue by Kunaguero110** [keiyoushi/tachiyomi-extensions-source#1762] opened 2024-03-08 04:56 UTC
### Source information

Shinigami 1.4.53

### Source language

Indonesia

### Source new URL

https://shinigami.cx

### Other details

![Screenshot_20240308-115544133](https://github.com/keiyoushi/extensions-source/assets/106704494/0a665003-4696-4b5e-986a-474bb8736a03)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-03-08 05:06
Duplicate of #1708

**Closed as not planned by vetleledaal** 2024-03-08 05:06 UTC
Labels: Bug, Duplicate, Domain changed
