### ISSUE TITLE
Asura scan(url is changed thats why ext not working)

### ISSUE THREAD

**Issue by Gamermemer** [keiyoushi/tachiyomi-extensions-source#5247] opened 2024-09-26 19:24 UTC
### Source information

Asura Scan

### Source language

English

### Source new URL

Www.asurascan.com

### Other details

So the website url is changed so ext is not working

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-26 19:27
Duplicate of #5241

Haven't we been over this? Search the existing issues before opening a new one, and acknowledging that you did when you clearly didn't

**Closed as completed** 2024-09-26 19:29 UTC
Labels: Bug, Domain changed
