### ISSUE TITLE
renewal request 

### ISSUE THREAD

**Issue by Vis2772** [keiyoushi/tachiyomi-extensions-source#6803] opened 2024-12-25 06:44 UTC
### Source name

scan-manga

### Source language

french

### Source link

https://m.scan-manga.com/?po

### Other details

the extension is no longer functional and must be renewed 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-25 07:03
Duplicate of #2232, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

Also, wrong issue request, this is for when the site is dead & gone. But again, already reported before

**Closed as not planned by Smol-Ame** 2024-12-25 07:03 UTC
Labels: Duplicate, Source is down
