### ISSUE TITLE
KomikIndoID change link url

### ISSUE THREAD

**Issue by Hahagun1** [keiyoushi/tachiyomi-extensions-source#6513] opened 2024-12-07 02:53 UTC
### Source information

KomikIndoId 1.4.14

### Source language

Indonesia

### Source new URL

https://komikindo.pw/

### Other details

![Screenshot_2024-12-07-10-52-17-177_com dark animetailv2-edit](https://github.com/user-attachments/assets/3f0a96c2-2763-44f9-961b-3ea7c0ffa70e)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TheKingTermux** [comment] 2024-12-07 04:47
Duplicate of #6513

**Comment by clyezen** [comment] 2024-12-07 11:26
Change url , the manga site is https://komikindo.cz/ and the website hub is https://komikindo.pw/
 the first i see on current webview is https://komikindo.cz/ and need goting to https://komikindo.pw/ for reading

**Comment by Smol-Ame** [comment] 2024-12-07 11:54
It's already been reported before as the bot message told you, no need to reiterate. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Comment by Smol-Ame** [comment] 2024-12-07 11:57
@vyerie No need to reiterate on the issue request about the change.

Earlier message I sent (and removed, cause I thought you replied to your own duplicate issue) was for you. Next time search the existing issues before opening a duplicate one, and acknowledging that you did when you didn't.

**Closed as completed** 2024-12-07 21:02 UTC
Labels: Bug, Domain changed, Valid
