### ISSUE TITLE
vortex scans domain changed or something 

### ISSUE THREAD

**Issue by Rasun0** [keiyoushi/tachiyomi-extensions-source#5861] opened 2024-11-03 12:29 UTC
### Source information

vortex scans 1.4.38

### Source language

English 

### Steps to reproduce

all titles form current website is gone it should be their but none r their they r moved to new website https://vortexscans.org/home this ig.
![Screenshot_2024_1103_175541](https://github.com/user-attachments/assets/02dab162-f687-4a2e-92b4-f41aa551d33c)

### Expected behavior

all titles should be in the https://vortextoon.com/home but none r their .

### Actual behavior

all titles should be on the https://vortextoon.com/home but now all r in https://vortexscans.org/home 

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

![Screenshot_2024_1103_175541](https://github.com/user-attachments/assets/365b9ecb-479f-4bd2-9893-00c0f94aea32)
they changed the domain or something like that ig .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-03 12:32
Duplicate of #5169

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned by Smol-Ame** 2024-11-03 12:32 UTC
Labels: Bug
