### ISSUE TITLE
Null Pointer exception on Asura Scans 1.4.39

### ISSUE THREAD

**Issue by SantanuLayek** [keiyoushi/tachiyomi-extensions-source#5212] opened 2024-09-25 04:20 UTC
### Source information

Asura Scans 1.4.39

### Source language

English

### Steps to reproduce

1. Go to the source.
2. Open any manhwa.
3. Refresh

### Expected behavior

1. Show new chapters that are released.

### Actual behavior

2. Null Pointer Exception : Null

### Mihon/Tachiyomi version

0.16.5

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-25 04:21
Duplicate of #5198 

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't

**Comment by SantanuLayek** [comment] 2024-09-25 04:22
I am very sorry, github didn't let me look into the issue list first, which is why I made this mistake. Once again I apologize.

**Closed as completed** 2024-09-25 04:22 UTC
Labels: Bug
