### ISSUE TITLE
Bakai 

### ISSUE THREAD

**Issue by Nerannnn** [keiyoushi/tachiyomi-extensions-source#1903] opened 2024-03-15 16:07 UTC
### Source information

Bakai 1.4.2

### Source language

Portuguese 

### Steps to reproduce

![Screenshot_20240315-114451](https://github.com/keiyoushi/extensions-source/assets/135178613/b610ebc2-609e-4fce-9270-601f0114fc43)

### Expected behavior

update manga normally

### Actual behavior

![Screenshot_20240315-114451](https://github.com/keiyoushi/extensions-source/assets/135178613/f2e7ef33-8049-423f-83cf-eb89bb909ece)

### Mihon/Tachiyomi version

0.15.2

### Android version

Android 11

### Other details

I have already sent several reports and my problem has not been resolved, I am probably being stupid and doing something wrong so I leave this message, please update the bakai extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-03-15 16:09
Duplicate of #1887

**Closed as not planned by AwkwardPeak7** 2024-03-15 16:09 UTC
Labels: Bug, Duplicate
