### ISSUE TITLE
cosmicScansID download bug

### ISSUE THREAD

**Issue by ChikaTempest** [keiyoushi/tachiyomi-extensions-source#5551] opened 2024-10-16 14:03 UTC
### Source information

CosmicScans.id 1.4.35

### Source language

indonesia

### Steps to reproduce

download the newest chapter. 
page not found after being download

### Expected behavior

download the newest chapter and read it as usual..

### Actual behavior

add the manhw to fav
download the newst page.
the download page can't be open and show page not found.

### Mihon/Tachiyomi version

mihon 0.16.5

### Android version

andorid 11

### Other details

this is only for the recent chapter.. but if i download the oldest chapter it can be open after being download

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2024-10-16 18:40
Please don't create duplicate Issue to bump up the old issue, you Aleardy make it before (#4865), If the old issue is no longer related, you can change it's contents, so do not create a new issue unless the old issue has been closed or locked, and don't forget to check the existing issues, who knows someone has already made one.

**Comment by Smol-Ame** [comment] 2024-10-16 19:23
Duplicate of #4865

Add to the **Other details** or comment in the previous issue when you find entries/chapters with this issue

**Closed as not planned by Smol-Ame** 2024-10-16 19:23 UTC
Labels: Bug
