### ISSUE TITLE
Kemono chapter images not opening error Fields [id, service, user, title, added, file] are required for type with serial name 'eu.kanade.tac...

### ISSUE THREAD

**Issue by kazu696** [keiyoushi/tachiyomi-extensions-source#6403] opened 2024-11-30 15:07 UTC
### Source information

Kemono

### Source language

Multi

### Steps to reproduce

1. Open any chapter of any entry in kemono extension
2. Got this error: Fields [id, service, user, title, added, file] are required for type with serial name 'eu.kanade.tac...

### Expected behavior

It should be open normally 

### Actual behavior

Getting this error
Fields [id, service, user, title, added, file] are required for type with serial name 'eu.kanade.tac...

### Mihon/Tachiyomi version

Tashiyomisy stable 1.11.0

### Android version

12

### Other details

![Screenshot_2024-11-30-20-02-38-072_eu kanade tachiyomi sy](https://github.com/user-attachments/assets/be380bf8-8cfb-4aa6-9a0e-02891fd750ab)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-11-30 15:10
Duplicate of #5883

**Closed as not planned by vetleledaal** 2024-11-30 15:10 UTC
Labels: Bug
