### ISSUE TITLE
Url change

### ISSUE THREAD

**Issue by Outer598** [keiyoushi/tachiyomi-extensions-source#5215] opened 2024-09-25 06:24 UTC
### Source information

Infernal void scans 1.4.38

### Source language

English

### Source new URL

https://hivetoon.net/

### Other details

The site was moved to a new domain 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-25 06:28
Duplicate of #5187 

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned** 2024-09-25 06:55 UTC
Labels: Bug, Domain changed
