### ISSUE TITLE
Spider Scans Extension Not Workinv 

### ISSUE THREAD

**Issue by ItsSheJoh** [keiyoushi/tachiyomi-extensions-source#6652] opened 2024-12-17 11:23 UTC
### Source information

Spider Scans 1.4.30

### Source language

English 

### Steps to reproduce

Spider scans extension not working in app but works fine in webview 
![Screenshot_2024-12-17-16-33-45-101_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/f18ee5d4-fcfe-4326-8a83-6c05de7e48e8)

### Expected behavior

Should show titles and covers 

### Actual behavior

Showing no results found 

### Mihon/Tachiyomi version

"0.17.1"

### Android version

"Android 11"

### Other details

Should work fine in the app but only working in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-12-17 20:41
Duplicate of #6641

**Closed as not planned by vetleledaal** 2024-12-17 20:41 UTC
Labels: Bug, Duplicate
