### ISSUE TITLE
Leercapitulo no carga capitulos 

### ISSUE THREAD

**Issue by BastiVader** [keiyoushi/tachiyomi-extensions-source#4753] opened 2024-08-25 15:08 UTC
### Source information

Leercapitulo 1.4.10

### Source language

Español

### Steps to reproduce

Entro a la fuente 
Elijo el manga 
Elijo el capitulo 
Lo abro y no carga 

### Expected behavior

Entro a la fuente 
Elijo el manga 
Elijo el capitulo 
Lo abro y leo el capítulo 

### Actual behavior

Entro a la fuente 
Elijo el manga 
Elijo el capitulo 
Lo abro y no carga 

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 12

### Other details

Es una de mis fuentes favoritas porfavor arreglenla 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment] 2024-09-13 13:50
I couldn't reproduce it. Maybe the limitRate gives the impression of not loading

**Comment by Smol-Ame** [comment] 2024-10-08 02:09
Closing since it's not reproducible currently.

If you experience it again, come to the Keiyoushi Discord repo-support channel to let us know/troubleshoot on the spot, or make a new issue if it happens again with more info.

**Closed as not planned by Smol-Ame** 2024-10-08 02:09 UTC
Labels: Bug
