### ISSUE TITLE
Coomer extension isn't loading chapters 

### ISSUE THREAD

**Issue by GDEKA** [keiyoushi/tachiyomi-extensions-source#6393] opened 2024-11-30 01:22 UTC
### Source information

Coomer 1.4.14

### Source language

Multiple 

### Steps to reproduce

1. Open the source.
2. Select any image.
3. Try to read the chapter.

### Expected behavior

The chapters will display normally, and will become available for download without any errors.

### Actual behavior

besides not being able to open the chapter, it is also not possible to download it 

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

![Screenshot_20241128-222042](https://github.com/user-attachments/assets/72777597-8546-4e6d-8c41-4be0a5f6ab5c)
This error message appears when you try to read the chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-11-30 11:52
Duplicate of #5883

(No, you are not expected to know these are sharing the same code)

**Closed as not planned by vetleledaal** 2024-11-30 11:52 UTC
Labels: Bug
