### ISSUE TITLE
Copy Add update Dilar

### ISSUE THREAD

**Issue by LoverFreedom** [keiyoushi/tachiyomi-extensions-source#2136] opened 2024-03-28 11:48 UTC
### Source name

update Dilar

### Source link

https://github.com/komikku-app/komikku-extensions/tree/master/src/ar/dilar

### Source language

Arabic

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-03-28 11:58
Extension already exist - https://keiyoushi.github.io/extensions/#ar.dilar

If you're reporting a bug with the current extension, you're using the wrong issue template.
If you're asking for a mirror to be added, that would be a duplicate of #1945

**Closed as not planned by vetleledaal** 2024-03-28 11:58 UTC
Labels: Source request
