### ISSUE TITLE
Asurascan

### ISSUE THREAD

**Issue by zephyrxk** [keiyoushi/tachiyomi-extensions-source#4178] opened 2024-07-23 13:53 UTC
### Source information

Asura Scans 1.4.34

### Source language

ENGLISH 

### Steps to reproduce

Just open the extension

### Expected behavior

Showing the list of manhuwa 

### Actual behavior

Could not load the list of manhuwa 

### Mihon/Tachiyomi version

MIHON 0.16.5

### Android version

Android 14

### Other details

Opening the web view shows that the site loads properly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-07-23 14:14
Duplicate of #4167

**Closed as not planned** 2024-07-23 14:15 UTC
Labels: Bug, Duplicate
