### ISSUE TITLE
"No pages found" issue for ReadComicOnline extension

### ISSUE THREAD

**Issue by amriteshs** [keiyoushi/tachiyomi-extensions-source#4067] opened 2024-07-17 05:13 UTC
### Source information

ReadComicOnline 1.4.20

### Source language

English

### Steps to reproduce

1. Add a comic using the extension to the Mihon library.
2. Open a chapter/issue to read.

### Expected behavior

The issue/chapter should open and be available for reading.

### Actual behavior

After briefly loading, "No pages found" error displayed.
![WhatsApp Image 2024-07-17 at 15 08 11](https://github.com/user-attachments/assets/e63b325d-99d5-4e36-8748-da07392aaf8e)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-07-17 05:17
Duplicate of #4028

**Closed as not planned** 2024-07-17 05:17 UTC
Labels: Bug, Duplicate
