### ISSUE TITLE
999hentai not working

### ISSUE THREAD

**Issue by Zethzune** [keiyoushi/tachiyomi-extensions-source#4150] opened 2024-07-21 16:47 UTC
### Source information

999hentai 1.4.6

### Source language

Multi/English 

### Steps to reproduce

1. Try opening the ext. 
2. See all manga/titles with broken covers
3. Select any, then try opening 1 chapters.. it won't load

1. Similar to already in the library, 
2. Select any titles on 999hentai category/ext. 
3. Try refreshing the manga, the cover will become broken, 
4. Similarly, the chapters won't load.
![Screenshot_20240722_002635_Mihon](https://github.com/user-attachments/assets/e77eef94-cbf3-4823-8f9a-177f4cf12732)

### Expected behavior

With working covers, and working chapters available. 

### Actual behavior

Broken covers and the chapters won't load..

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13

### Other details

Fortunately the downloaded chapters was working just fine, but it's covers become broken if the title is refreshed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-07-22 13:09
Duplicate of #4151

**Closed as not planned** 2024-07-22 13:10 UTC
Labels: Bug, Duplicate
