### ISSUE TITLE
Wolf.com Manhua Raws Source Request

### ISSUE THREAD

**Issue by mentlmelody** [keiyoushi/tachiyomi-extensions-source#5674] opened 2024-10-24 07:09 UTC
### Source name

 늑대닷컴  /  Wolf.com

### Source link

wfwf354.com

### Source language

Korean

### Other details

Hosts raws for korean manhua / webtoons.

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-24 07:12
Duplicate of #3987

Search the existing issues before opening a new one

**Closed as not planned by Smol-Ame** 2024-10-24 07:12 UTC
Labels: Source request

**Comment by mentlmelody** [comment] 2024-10-24 07:21
So sorry. I did search but that issue didn't pop up cause it's using an old domain name.
