### ISSUE TITLE
Kappa Beast HTTP 404 error

### ISSUE THREAD

**Issue by manti-X** [keiyoushi/tachiyomi-extensions-source#5439] opened 2024-10-08 16:01 UTC
### Source information

Kappa Beast 1.4.30

### Source language

English

### Steps to reproduce

1. Open the source

### Expected behavior

Should display a list of mangas

### Actual behavior

HTTP 404 error

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

The site can be visited through webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-08 18:49
Duplicate of #4885

**Closed as not planned by Smol-Ame** 2024-10-08 18:49 UTC
Labels: Bug
