### ISSUE TITLE
Bakai erro 404

### ISSUE THREAD

**Issue by OceaN90S** [keiyoushi/tachiyomi-extensions-source#1925] opened 2024-03-16 14:12 UTC
### Source information

Bakai 1.4.2

### Source language

Português (br)

### Steps to reproduce

The extension gives the 404 error, not loading the extension's home page or searching, other than that, the manga already included in the library works normally 
![Screenshot_20240316-103128](https://github.com/keiyoushi/extensions-source/assets/156086953/615d9958-c94c-4035-ab1b-d9f1a8bfc5a4)
![Screenshot_20240316-103718](https://github.com/keiyoushi/extensions-source/assets/156086953/902dd1f5-181a-4f73-bc52-670b8032ad08)

### Expected behavior

Loaded extension sleeve information 

### Actual behavior

Instead of showing the manga it gets the 404 error

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Other details

Sorry if it seemed confusing, I don't have English as my native language, please answer this and I use this extension daily, thank you for everything 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-03-16 14:20
Duplicate of #1887

**Closed as not planned by AwkwardPeak7** 2024-03-16 14:20 UTC
Labels: Bug, Duplicate
