### ISSUE TITLE
Change the url

### ISSUE THREAD

**Issue by Valz3r0** [keiyoushi/tachiyomi-extensions-source#5589] opened 2024-10-19 04:28 UTC
### Source information

Olympus Scanlation 1.4.9 

### Source language

Spanish 

### Source new URL

https://zonaolympus.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2024-10-19 04:55
Duplicate of #5576

**Comment by Smol-Ame** [comment] 2024-10-19 07:03
Idiot, learn to read otherwise why bother getting the extension fixed.

The bot message in each of your duplicate issues told you why it was closed. Someone else had already reported it, along with a handful of duplicate issues made before you.

**Closed as not planned by Smol-Ame** 2024-10-19 07:03 UTC
Labels: Bug, Domain changed
