### ISSUE TITLE
extension not work

### ISSUE THREAD

**Issue by Etsh72** [keiyoushi/tachiyomi-extensions-source#4046] opened 2024-07-16 12:40 UTC
### Source name

Galaxy manga

### Source language

Arabic

### Source link

https://hojdy.xyz/webtoons/

### Other details

https://hojdy.xyz/webtoons/romance/home

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-07-16 12:43
Duplicate of #3984

and next time use domain change template instead of source down one

**Closed as not planned** 2024-07-16 12:44 UTC
Labels: Duplicate, Source is down
