### ISSUE TITLE
pixivコミック has some Troubleshooting

### ISSUE THREAD

**Issue by simulationcard** [keiyoushi/tachiyomi-extensions-source#6151] opened 2024-11-19 06:04 UTC
### Source information

pixivコミック 

### Source language

日本語

### Steps to reproduce

![IMG_20241119_134838](https://github.com/user-attachments/assets/40fe3955-b043-4569-870e-c6132c317298)
![Uploading IMG_20241119_140046.jpg…]()

### Expected behavior

Fluently watching  comics

### Actual behavior

when  I opened comics，it said‘HTTP error 404’

### Mihon/Tachiyomi version

0.17.0

### Android version

Android12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Rstoroniomi** [comment] 2024-11-19 06:05
![正在上传 IMG_20241119_140046.jpg…]()

**Comment by Rstoroniomi** [comment] 2024-11-19 06:07
![IMG_20241119_140726.jpg](https://github.com/user-attachments/assets/783b7370-9d54-450b-8285-b55b0aeaef62)

**Comment by akir45** [comment] 2024-11-21 01:55
It is duplicate of https://github.com/keiyoushi/extensions-source/issues/5179

**Closed as not planned** 2024-11-21 02:08 UTC
Labels: Bug, Duplicate
