### ISSUE TITLE
Change in URL 

### ISSUE THREAD

**Issue by Jigoku69** [keiyoushi/tachiyomi-extensions-source#5201] opened 2024-09-24 19:55 UTC
### Source information

Change of URL in infernal void scans

### Source language

English

### Steps to reproduce

![Screenshot_2024-09-25-01-23-57-54_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/c5d35538-c812-4268-bdbf-5b06a2c7a6c2)
![Screenshot_2024-09-25-01-23-53-47_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/5b43bd1e-3ce1-4d81-abb2-da7e8a921de3)

### Expected behavior

Shhs

### Actual behavior

Zvbz

### Mihon/Tachiyomi version

0.16.5

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-09-24 19:57
Duplicate of #5187

**Closed as not planned by vetleledaal** 2024-09-24 19:57 UTC
Labels: Bug
