### ISSUE TITLE
Olympuss

### ISSUE THREAD

**Issue by heinor1** [keiyoushi/tachiyomi-extensions-source#2173] opened 2024-03-30 11:03 UTC
### Source information

tachiyomi-es.olympusscanlation-v1.4.7

### Source language

Español 

### Source new URL

https://visorolym.com/

### Other details

Actualización de URL

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-03-30 11:30
The domain is already used in the extension.

Duplicate of #1819 , possibly

**Closed as not planned by vetleledaal** 2024-03-30 11:30 UTC
Labels: Bug, Domain changed
