### ISSUE TITLE
Luratoons is nor working

### ISSUE THREAD

**Issue by 0nur65** [keiyoushi/tachiyomi-extensions-source#5878] opened 2024-11-04 01:08 UTC
### Source name

Lura toon 

### Source language

Portuguese 

### Source link

https://luratoons.com/

### Other details

Good morning everyone, I came here to report the problem of an extension called Lura Toons, well the Lura Toons website charges a monthly subscription for people to have access to their translated works, so naturally their extension does not work on Mihon, however when paying a subscription and logging into your account through WebView the extension worked perfectly but two days ago it stopped working even with the website working normally, does anyone know how to help me? Sorry if there are translation errors
The Lura Toons website had already been changed a long time ago, I remember that at the time I was able to download another extension with the luratons url. However, a few days ago the extension simply stopped displaying the new chapters in the Mihon app, but when entering the site through WebView the site continues to function normally when you have an account logged into it, it simply gives a message saying that it cannot find new chapters in the app
![Screenshot_20241102-095920_Mihon](https://github.com/user-attachments/assets/16184afb-7553-49c0-9f4c-5a9d12d86a21)
![Screenshot_20241102-095929_Mihon](https://github.com/user-attachments/assets/6caa2645-b749-4cd0-b2db-6b1f18f5c1db)
![Screenshot_20241102-095940_Mihon](https://github.com/user-attachments/assets/8eceec4d-69ed-4828-ac18-ec78b1b0143b)
![Screenshot_20241102-095952_Mihon](https://github.com/user-attachments/assets/e202a331-dbee-4950-9642-bc339ef5ed3b)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-04 07:18
Duplicate of #5739

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you didn't.

**Closed as not planned by Smol-Ame** 2024-11-04 07:18 UTC
Labels: Source is down

**Comment by 0nur65** [comment] 2024-11-05 14:46
is a new problem
