### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ashli1224** [keiyoushi/tachiyomi-extensions-source#6170] opened 2024-11-19 22:30 UTC
### Source information

LikeManga 1.4.4

### Source language

English

### Steps to reproduce

1. Download likemanga 
2. Open it

### Expected behavior

Should be able to read and browse manga.

### Actual behavior

![Screenshot_20241119-162125_Mihon](https://github.com/user-attachments/assets/81743d4f-8641-4777-97b2-f3922625a067)
When I try to read chapters from LikeManga it says chapters not found

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 11

### Other details

Going through webview works, other extensions work, no cloudfare problems, cleared cache and cookies, changed my DNS over https, and I changed my user agent string over 5 times and problem still continued

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-11-19 23:12
Duplicate of #6163

**Closed as not planned by vetleledaal** 2024-11-19 23:12 UTC
Labels: Bug

**Comment by ashli1224** [comment] 2024-11-19 23:17
The extension is update to the new url. It directs me to LikeManag.in but I still can't view it through the app or read/browse manhwa

**Comment by vetleledaal** [comment] 2024-11-19 23:21
The linked issue is still open, meaning it is not fixed yet. You can subscribe to that issue to get future updates.
