### ISSUE TITLE
Mangahub not loading images

### ISSUE THREAD

**Issue by Di-kello** [keiyoushi/tachiyomi-extensions-source#6896] opened 2024-12-29 07:13 UTC
### Source information

Mangahub 1.4.39

### Source language

English 

### Steps to reproduce

The extension becomes unusable after extended use and starts displaying "API limit exceeded visit mangahub.io to continue reading" 

### Expected behavior

Images should load

### Actual behavior

Images not showing due to API limit 

### Mihon/Tachiyomi version

Tachiyomi j2k 1.7.4

### Android version

Android 9

### Other details

![Screenshot_20241229-075856_TachiyomiJ2K](https://github.com/user-attachments/assets/a9ef0d0b-6c07-4877-b9c6-d8ec5457d923)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-12-29 07:41
Duplicate of #6573

**Closed as not planned by vetleledaal** 2024-12-29 07:41 UTC
Labels: Bug, Duplicate
