### ISSUE TITLE
Arab hentai 

### ISSUE THREAD

**Issue by Demonkingdiablo** [keiyoushi/tachiyomi-extensions-source#6824] opened 2024-12-26 20:20 UTC
### Source name

Arabs hentai

### Source language

Arabic

### Source link

Http://arabshentai

### Other details

There's no chapter in the manga

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-12-26 20:47
So, to read a chapter you need to go through a 'link shortener'. The whole process is (with 15s delay between most steps):
- Accept cookies (GDPR thing)
- Subscribe to a channel and watch + like a video
- Solve a captcha
- Click on an AD
- Subscribe to a channel and watch + like a video
- Click on an AD
- Subscribe to a channel and watch + like a video
- Click on an AD

The link you get in the end links back to the site, the URL is not predictable. I think the extension should be removed instead, as automating the process is next to impossible and people won't wait 2 minutes for a chapter to load.

**Comment by vetleledaal** [comment] 2024-12-26 21:04
Duplicate of #3925

**Closed as not planned by vetleledaal** 2024-12-26 21:04 UTC
Labels: Bug, Duplicate, Valid

**Comment by Demonkingdiablo** [comment] 2024-12-28 07:54
i want to read the chapter in the app not the website or WebView

**Comment by Demonkingdiablo** [comment] 2024-12-28 07:59
![Uploading Screenshot_2024-12-28-09-58-01-67.jpg…]()
