### ISSUE TITLE
（包子漫画导航）Baozimh.org v1.4.28 is not working correctly

### ISSUE THREAD

**Issue by SWWim** [keiyoushi/tachiyomi-extensions-source#2323] opened 2024-04-10 01:53 UTC
### Source information

（包子漫画导航）Baozimh.org v1.4.28

### Source language

Chinese

### Steps to reproduce

Opened the [Baozimh.org](https://baozimh.org/) v1.4.28 extension.
Tried using it normally, but the extension displayed "No results found."
**However, using the "Open in WebView" option allows for normal browsing.**
![562d56a8600b47b87a8d407d39f14bb](https://github.com/keiyoushi/extensions-source/assets/30291483/c8630fe2-f344-4a05-b5c5-9b4e85906632)

![0e2f9430d85e0b8491df9b7550c8d11](https://github.com/keiyoushi/extensions-source/assets/30291483/4503504d-bca5-42f0-baff-c6f28d9df47c)

### Expected behavior

Expected behavior: The [Baozimh.org](https://baozimh.org/) v1.4.28 extension should display manga content correctly and allow for searching manga content without issues.
![fde2a8ccb19114aa682db363eda9786](https://github.com/keiyoushi/extensions-source/assets/30291483/7cd2b444-a7bf-452a-9887-89e3b060b753)

### Actual behavior

the extension displayed "No results found."
Attempted to search for manga content, but the extension displayed the error message: "HTTP [404.check](https://404.check/) website in WebView."
![b47052c5fdb81600d1c85216cc3dfab](https://github.com/keiyoushi/extensions-source/assets/30291483/7ea3d7c2-cd54-44db-b7ae-0c864e033390)
![a4e1f64bea6a09953c5141ece3a9502](https://github.com/keiyoushi/extensions-source/assets/30291483/0cc9dba6-20c8-412b-b902-18163bb643fc)

### Mihon/Tachiyomi version

0.16.5

### Android version

harmony 4.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-04-11 06:38
Duplicate of #826

**Closed as not planned** 2024-04-11 06:38 UTC
Labels: Bug, Duplicate
