### ISSUE TITLE
ReadComicOnline Images not loading

### ISSUE THREAD

**Issue by wattermany2** [keiyoushi/tachiyomi-extensions-source#5124] opened 2024-09-19 03:28 UTC
### Source information

ReadComicOnline 1.4.26

### Source language

English

### Steps to reproduce

1. Open Comic
2. start

### Expected behavior

Images load

### Actual behavior

they don't
![Screenshot_20240918_230713_TachiyomiSY](https://github.com/user-attachments/assets/3f4f5685-0d4c-4a75-b88f-1b694e935646)
![Screenshot_20240918_231536_TachiyomiSY](https://github.com/user-attachments/assets/b1bf551a-fa53-4030-bc9b-0b0875279781)
![Screenshot_20240918_231703_TachiyomiSY](https://github.com/user-attachments/assets/e649575e-19b6-41f4-96ad-cfc2eb56bc00)

### Mihon/Tachiyomi version

sy r564

### Android version

Android 13

### Other details

i tried askin support in mihon and got timed so sry if im annoying yall

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-19 03:32
Duplicate of #4115

Search the existing issues before making a new one, and acknowledging that you did when you didn't

**Comment by wattermany2** [comment] 2024-09-19 03:34
my bad

**Closed as not planned** 2024-09-19 03:45 UTC
Labels: Bug
