### ISSUE TITLE
Foi trocado o URL da extensão Sussy Scan. PT-BR

### ISSUE THREAD

**Issue by Vladmirrr** [keiyoushi/tachiyomi-extensions-source#6355] opened 2024-11-27 21:10 UTC
### Source information

Sussy Scan 1.4.41

### Source language

Português PT-BR

### Source new URL

https://new.sussytoons.site/

### Other details

O site antigo ainda está no ar mais pararam de atualizá-lo e só estão atualizando o novo site.
![Screenshot_20241127-175903](https://github.com/user-attachments/assets/39bae0c7-12f8-411b-a1e3-4f8f18c3eaa2)
![Screenshot_20241127-175911](https://github.com/user-attachments/assets/82d3d8ee-5d9b-4e44-82fd-a26bb79856ee)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-11-27 21:48
Duplicate of #6034

**Closed as not planned by vetleledaal** 2024-11-27 21:48 UTC
Labels: Bug, Domain changed
