### ISSUE TITLE
Http 404 Mhscans

### ISSUE THREAD

**Issue by Reydelasombras** [keiyoushi/tachiyomi-extensions-source#2979] opened 2024-05-12 04:28 UTC
### Source information

MHScans

### Source language

español

### Source new URL

https://lectormh.com/

### Other details

Al parecer cambiaron el nombre 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by br14n-sol** [comment] 2024-05-12 04:39
#2959 It should have fixed it, wait a while for the changes to compile.

**Comment by AwkwardPeak7** [comment] 2024-05-12 04:53
duplicate of #2947

**Closed as not planned** 2024-05-12 04:53 UTC
Labels: Bug, Duplicate, Domain changed
