### ISSUE TITLE
mgkomik bug, The comic list does not appear and the webview display is broken

### ISSUE THREAD

**Issue by VQA-06** [keiyoushi/tachiyomi-extensions-source#6487] opened 2024-12-05 16:51 UTC
### Source information

MG Komik 1.4.51

### Source language

Indonesia

### Steps to reproduce

when searching for comics, the comic list doesn't appear and when opening the webview, the webview is broken
![Screenshot_20241205-233037](https://github.com/user-attachments/assets/f8e74c41-e9ce-4bb5-8d18-b37a175a9581)

### Expected behavior

this should show the comic list and the web display on webview is not broken.

### Actual behavior

What actually happened was that the comic list didn't appear and the web display on webview was broken.

### Mihon/Tachiyomi version

0.17.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-05 16:56
Seems to work fine. Change your user-agent, restart the app, pass Cloudflare, and try again. Come to the Keiyoushi Discord repo-support channel for help, additional questions, or just basic troubleshooting in general.

Also/Otherwise, duplicate of #6358, though I was able to load it up after passing Cloudflare, choosing their website (in their page portal), and passing that Cloudflare verification.

![Screenshot_20241206_005418_Mihon.png](https://github.com/user-attachments/assets/eb791b81-de6b-429f-86a0-010a0f0b3527)

**Closed as not planned** 2024-12-05 16:56 UTC
Labels: Bug
