### ISSUE TITLE
ReadComicOnline download error » "java.lang.Excepetion: Solce capthac in WebView" or "Error 400"

### ISSUE THREAD

**Issue by pbmzbr** [keiyoushi/tachiyomi-extensions-source#4918] opened 2024-09-04 15:12 UTC
### Source information

ReadComicOnline

### Source language

English

### Steps to reproduce

1. Install the source "ReadComicOnline"
2. Look for a comic book and add it to your library
3. Download the chapters

### Expected behavior

The chapters will be downloaded.

### Actual behavior

Chapters are NOT downloaded.

Server 1
![image](https://github.com/user-attachments/assets/f012d7fc-a77f-48d4-9ae3-5d93e17bb37f)

![image](https://github.com/user-attachments/assets/6590d50a-3b4a-45e8-98f2-e74412312d4f)
![image](https://github.com/user-attachments/assets/1b60b920-7b3d-479d-a834-1cb8f846dfd6)
![image](https://github.com/user-attachments/assets/d5b36f84-b215-4afe-ba32-94d6baf829d8)
![image](https://github.com/user-attachments/assets/7446807e-1f62-493c-9335-d34fd507a10a)

Server 2
![image](https://github.com/user-attachments/assets/38a2e1cd-9f58-42c0-b058-ccd5b7af1b9f)
![image](https://github.com/user-attachments/assets/7a74da4c-8db8-40ae-8732-2082987b24b2)
![image](https://github.com/user-attachments/assets/e4ba97f1-b234-44a5-a77d-1ad8b59a5123)

Webview
![image](https://github.com/user-attachments/assets/26edf614-1ae2-458d-b0b3-7ea6e46e77de)
![image](https://github.com/user-attachments/assets/5097af26-b7cf-4dc4-93ba-f61c212c6ca3)
No problems with CAPTCHA or Cloudflare
I have already done Clear cookies
I have already done Clear WebView data

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-09-04 15:24
Duplicate of #4115

**Closed as not planned by AwkwardPeak7** 2024-09-04 15:24 UTC
Labels: Bug

**Comment by pbmzbr** [comment] 2024-09-04 15:29
> Duplicate of #4115

Hello [AwkwardPeak7](https://github.com/AwkwardPeak7),
I know the bugs look a like, but there is no solution in the previous bug and I added more information than the previous one.

**Comment by AwkwardPeak7** [comment] 2024-09-04 15:32
there is no solution because the website kept breaking the extension when we were fixing it

**Comment by pbmzbr** [comment] 2024-09-05 07:13
> there is no solution because the website kept breaking the extension when we were fixing it

Oh!!! OK. I didn't know and had no idea about this. Thank you for let me know.
