### ISSUE TITLE
add hoduhodu

### ISSUE THREAD

**Issue by wolfkingal2000** [keiyoushi/tachiyomi-extensions-source#5548] opened 2024-10-15 21:28 UTC
### Source name

hoduhodu

### Source link

https://t44.hoduhodu.com/

### Source language

Korean

### Other details

18+=yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-10-16 05:55
Duplicate of #4880

**Closed as not planned by AwkwardPeak7** 2024-10-16 05:55 UTC
Labels: Source request
