### ISSUE TITLE
changing the Website design "Manga pro "

### ISSUE THREAD

**Issue by fool0klein** [keiyoushi/tachiyomi-extensions-source#6739] opened 2024-12-21 18:18 UTC
### Source information

Manga pro 1.4.33

### Source language

Arabic

### Steps to reproduce

Manga pro change the Website design and resulted in this :

1- Open the extension from (Browse) then (Sources).
2- you will get the message
 "No results found".

### Expected behavior

"This should happen for example":
![IMG_20241221_191536](https://github.com/user-attachments/assets/bb7c8eda-8768-430c-a215-c0eb629f50fd)

### Actual behavior

![397576848-a29a5194-a349-4b02-83f3-a94e3b981749](https://github.com/user-attachments/assets/44c5f626-e546-43f7-8245-ffcb0b20fef1)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 12

### Other details

Nothing for now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-12-22 20:27
Duplicate of #6702

**Closed as not planned by vetleledaal** 2024-12-22 20:27 UTC
Labels: Bug, Duplicate
