### ISSUE TITLE
Merlin Scans: "No results found"

### ISSUE THREAD

**Issue by kyoyacchi** [keiyoushi/tachiyomi-extensions-source#5648] opened 2024-10-22 18:28 UTC
### Source information

Merlin Scans 1.4.36

### Source language

Turkish

### Steps to reproduce

Try using merlin scans

### Expected behavior

It should work

### Actual behavior

It shows no results found. Website is up tho.

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-22 19:29
Duplicate of #5175

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-10-22 19:29 UTC
Labels: Bug
