### ISSUE TITLE
Manga Demon change their url

### ISSUE THREAD

**Issue by ReiErix** [keiyoushi/tachiyomi-extensions-source#4859] opened 2024-08-30 23:40 UTC
### Source information

Manga Demon 1.4.12

### Source language

English

### Source new URL

https://demonicscans.org/

### Acknowledgements

- [x] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-30 23:40
Duplicate of #4770 

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't

**Closed as not planned** 2024-08-30 23:46 UTC
Labels: Bug, Domain changed
