### ISSUE TITLE
Problema de recientes en Hitomi

### ISSUE THREAD

**Issue by lukzvX** [keiyoushi/tachiyomi-extensions-source#6687] opened 2024-12-19 02:22 UTC
### Source information

Hitomi

### Source language

Ingles 

### Steps to reproduce

In recent times in Hitomi on the mihon app it comes out 
Missing FieldException: Fields [haswebp, hasjxl] are required for type with serial name 'eu.kanade.tachiyomi.extension.all.hitomi.ImageFile', but they were missing at path: $.files[0]

### Expected behavior

...

### Actual behavior

...

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 10

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-19 02:23
1. Duplicate of #6659, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
2. For future issue requests, actually fill out the whole thing

**Closed as not planned** 2024-12-19 02:22 UTC
Labels: Bug
