### ISSUE TITLE
Dillar : Multiple links

### ISSUE THREAD

**Issue by DemonEmperor1** [keiyoushi/tachiyomi-extensions-source#2060] opened 2024-03-23 15:18 UTC
### Source name

Dilar

### Source language

Arabic 

### Describe your suggested feature

The VPN requires the link (https://dilar.tube) and this link does not require the VPN program, it works without any problems (https://golden.rest)

### Other details

See pictures of the old link and the new link 

1- Old first link  :

![Screenshot_٢٠٢٤٠٣٢١-٢١٣٣٢٨_Mihon](https://github.com/komikku-app/komikku-extensions/assets/162794866/1d3e9c4a-4efe-4d4a-9219-1473ac20d57d)
![Screenshot_٢٠٢٤٠٣٢١-٢١٣٣٣١_Mihon](https://github.com/komikku-app/komikku-extensions/assets/162794866/80751e4f-234c-4b39-861d-bc6016f0f3fc)

2- The second link : 

![Screenshot_٢٠٢٤٠٣٢١-٢١٣٤٤٤_Chrome](https://github.com/komikku-app/komikku-extensions/assets/162794866/4ec6b5d9-8762-4427-9aa8-8057cc47c57a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-03-23 15:24
Duplicate of #1945

**Closed as not planned** 2024-03-23 15:24 UTC
Labels: Duplicate, Feature request
