### ISSUE TITLE
MHScans carga de capitulos 

### ISSUE THREAD

**Issue by hANXITOO** [keiyoushi/tachiyomi-extensions-source#5750] opened 2024-10-28 23:25 UTC
### Source information

MHScans 1.4.40

### Source language

español

### Steps to reproduce

al actualizar  la extensión no actualiza la lista de capitulos y imagen, tampoco permite leer los capitulos 

### Expected behavior

lo normal es que al alctualizar se puede visualizar dicho contenido 

### Actual behavior

no hay capitulos, ocurrio despues de actualizar pero si en la pagina directa si hay capitulos 

### Mihon/Tachiyomi version

0.17.0

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-29 08:13
Duplicate of #5693

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-10-29 08:13 UTC
Labels: Bug
