### ISSUE TITLE
https://www.hijala.com

### ISSUE THREAD

**Issue by anas7ye** [keiyoushi/tachiyomi-extensions-source#1826] opened 2024-03-11 22:47 UTC
### Source name

Hijala

### Source link

https://www.hijala.com/

### Source language

Arabic 

### Other details

{"name":"Tachiyomi: Hijala","pkg":"eu.kanade.tachiyomi.extension.ar.hijala","apk":"tachiyomi-ar.hijala-v1.4.8.apk","lang":"ar","code":8,"version":"1.4.8","nsfw":0,"sources":[{"name":"Hijala","lang":"ar","id":"4536808529544021974","baseUrl":"https://www.hijala.com/"}]}
I hope you will remove the NullPointerExcePtion:null problem 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-03-11 23:06
Duplicate of #1812

**Closed as not planned by AwkwardPeak7** 2024-03-11 23:06 UTC
Labels: Duplicate, Source request

**Comment by anas7ye** [comment] 2024-03-11 23:10
Hello and welcome, I want to solve the problem of NullPointerExcePtion:null
In the source of hijala, the website link is https://www.hijala.com/.
Please respond and solve the problem as soon as possible, and I am sorry
for the inconvenience you are having.

في الاثنين، 11 مارس 2024 11:06 م AwkwardPeak7 ***@***.***>
كتب:
