### ISSUE TITLE
Manga Galaxy Not Showing Results

### ISSUE THREAD

**Issue by Kenn876** [keiyoushi/tachiyomi-extensions-source#1508] opened 2024-02-23 17:30 UTC
### Source information

Manga Galaxy 1.4.36

### Source language

English

### Steps to reproduce

1. Go to source
2. Pess on Manga Galaxy extension

### Expected behavior

The site should show the list of mangas and manhwas to read.

### Actual behavior

The site just shows "No results found"

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Other details

![Screenshot_20240224_012630](https://github.com/keiyoushi/extensions-source/assets/137243023/5a88a2f8-f022-4ec2-8e77-f3dc4519d4ed)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kantotero** [comment] 2024-02-24 01:42
I also experience this, it works on webview but the list doesn't show

**Comment by AwkwardPeak7** [comment] 2024-02-26 13:59
duplicate of #830

**Closed as not planned by AwkwardPeak7** 2024-02-26 13:59 UTC
Labels: Bug, Duplicate
