### ISSUE TITLE
Hentaifox not showing picture

### ISSUE THREAD

**Issue by NameLess1909** [keiyoushi/tachiyomi-extensions-source#5927] opened 2024-11-07 13:29 UTC
### Source information

Hentaifox 1.4.8

### Source language

English

### Steps to reproduce

1. open manga
2. The picture is not showing

### Expected behavior

![507397](https://github.com/user-attachments/assets/809ead46-4559-470c-85da-08b1c4492cc4)

### Actual behavior

![Screenshot_2024-11-07-20-26-19-88_855c71507a0c11b360d5d38f8d2d1c96](https://github.com/user-attachments/assets/1f2d35f5-2d3e-45e3-8ca3-2dcc8f11cbde)

### Mihon/Tachiyomi version

Tachiyomiaz v8.8.2-AZ

### Android version

Android 10

### Other details

The webview is fine i can read the manga and the picture is showing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-07 13:31
Duplicate of #5915

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Closed as not planned by Smol-Ame** 2024-11-07 13:31 UTC
Labels: Bug
