### ISSUE TITLE
Images dont load on some manga.

### ISSUE THREAD

**Issue by xxxcielxxx01** [keiyoushi/tachiyomi-extensions-source#4424] opened 2024-08-05 08:28 UTC
### Source information

Mangago 1.4.16

### Source language

English

### Steps to reproduce

This has all been done specifically on the mangago extension, I will open a chapter on any Manga. Which will load the first few pages (usually up to page 5), but then stop working. This just happens to some manga not all though.

### Expected behavior

Normally when pages doesn't load immediately when clicking a chapter. I will go back and reload the page and or restar app. And it will start working, but this has not happened the past few times i've tried.

### Actual behavior

First couple of pages will load, but after maybe 3 to 5 pages it shows the reload page button's. When I click on them, they still don't reload the page. Have tried downloading chapter and it won't let me download the chapter. I have also tried clearing my cookies and data. I have also tried uninstalling and reinstalling extension and restarting app.
![Screenshot_20240711_025524_Mihon](https://github.com/user-attachments/assets/c8c3620c-c68b-462a-9421-7cceb26aee9f)
![Screenshot_20240711_025534_Mihon](https://github.com/user-attachments/assets/fbbc8671-d6df-42cc-ad86-1d08681ef636)

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Other details

I had first tried asking To see if it was an app problem, because I noticed this started happening after the last update, but I was told that is an extension problem. So i'm just trying to see if there's a way to get this resolved. As I know, there was a recent update for the specific extension, but it did not fix that problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-08-05 08:54
Duplicate of #4005

**Comment by AwkwardPeak7** [comment] 2024-08-05 08:54
Try logging in to your account in webview, it may improve the situation

**Closed as not planned** 2024-08-05 08:54 UTC
Labels: Bug, Duplicate
