### ISSUE TITLE
Quantum scans no address associated with host

### ISSUE THREAD

**Issue by AryanMithbawkar** [keiyoushi/tachiyomi-extensions-source#6737] opened 2024-12-21 16:37 UTC
### Source information

1.4.31

### Source language

ENGLISH 

### Steps to reproduce

1. Search for quantum scans 
2. Open extension 

### Expected behavior

This should take you into extension view of website 

### Actual behavior

Shows not addressed associated with hostname
![Screenshot_20241221_220422_eu kanade tachiyomi j2k](https://github.com/user-attachments/assets/80cd747f-0225-4a13-b693-d654577bc03c)

### Mihon/Tachiyomi version

1.7.4

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment] 2024-12-21 18:10
Duplicate of #6677

**Closed as not planned by vetleledaal** 2024-12-21 18:10 UTC
Labels: Bug, Duplicate
