### ISSUE TITLE
Manga Cross extension no longer works (site & url update)

### ISSUE THREAD

**Issue by Nogooduser** [keiyoushi/tachiyomi-extensions-source#2582] opened 2024-04-26 14:28 UTC
### Source information

Manga Cross 1.4.5

### Source language

Japanese

### Steps to reproduce

1. Install latest Manga Cross extension
2. Try to open its catalogue or search a manga on it 

If you had a manga cross entry already in your library it also won't refresh

### Expected behavior

Source should work as normal.

### Actual behavior

Nothing works

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

[Manga Cross](https://mangacross.jp/) not only updated their name and url to Manga Champion, they also updated their entire website to have the same UI/app as other Akita Shoten publications (Young Champion for example is the same). Extension probably needs to be rewritten unless you've already made extensions for this software (not sure what it's called but the interface is really unique so it should be a dead giveaway, I think Young Animal also uses it)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-04-28 11:03
Duplicate of #2532

**Closed as not planned** 2024-04-28 11:04 UTC
Labels: Bug, Duplicate
