### ISSUE TITLE
Mh Scans no funciona

### ISSUE THREAD

**Issue by Striven100** [keiyoushi/tachiyomi-extensions-source#5781] opened 2024-10-30 13:12 UTC
### Source information

MHScan (es.mhscans)

### Source language

Español

### Steps to reproduce

No puedo actualizar el contenido y no hay paginas en los capitulos.

### Expected behavior

Mis manhwas de mhscan no funcionan, pero solo esos

### Actual behavior

Revisa la pagina y funciona bien, nose si cambio el url (manhuaonline.org)

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment] 2024-10-30 15:01
Duplicate of #5693

**Closed as not planned** 2024-10-30 15:11 UTC
Labels: Bug
