### ISSUE TITLE
Happymh pages won't load 

### ISSUE THREAD

**Issue by RadStorm04** [keiyoushi/tachiyomi-extensions-source#1212] opened 2024-02-12 22:39 UTC
### Source information

Happymh 1.4.7

### Source language

中文

### Steps to reproduce

1. Open manga from said source
2. Failed to load pages (blank)

### Expected behavior

Load & show pages normally

### Actual behavior

Even with going through the webview cloudflare verification the pages still won't load in app

### Mihon/Tachiyomi version

Mihon 0.16.3

### Android version

Android 14

### Other details

It could be the case that the website temporarily up the security or changed something to handle the potential load increase during Chinese new year, but it's just a uneducated guess

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2024-02-13 10:01
Duplicate of #1181

**Closed as not planned by stevenyomi** 2024-02-13 10:01 UTC
Labels: Bug, Duplicate
