### ISSUE TITLE
Kisslove extension doesn't update manga

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#3216] opened 2024-05-24 15:32 UTC
### Source information

KissLove

### Source language

Japanese

### Steps to reproduce

1) Go to any manga on that extension
2) Refresh the manga

### Expected behavior

Manga should be updated

### Actual behavior

![Screenshot_20240524_211050_TachiyomiSY](https://github.com/keiyoushi/extensions-source/assets/87926066/5e403d17-18b4-488e-b5b1-e4d7fb074202)

### Mihon/Tachiyomi version

TachiyomiSY stable 1.10.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-05-24 15:34
Duplicate of #3197

**Closed as not planned** 2024-05-24 15:34 UTC
Labels: Bug, Duplicate
