### ISSUE TITLE
Mangahere some http error 500

### ISSUE THREAD

**Issue by Sundogg17** [keiyoushi/tachiyomi-extensions-source#4823] opened 2024-08-29 14:42 UTC
### Source information

Manga here 1.4.19

### Source language

English 

### Steps to reproduce

Open source, some gives http 500 error. Web view still works for them.

Basically S
Some titles open in app, some won't but will still opeb in webview 

### Expected behavior

Open any title and work

### Actual behavior

Some open, some won't. But webview still works

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-29 16:50
Duplicate of #4819

**Closed as not planned** 2024-08-29 16:53 UTC
Labels: Bug, Duplicate
