### ISSUE TITLE
The blankscans extension not working properly 

### ISSUE THREAD

**Issue by demon456blade** [keiyoushi/tachiyomi-extensions-source#6781] opened 2024-12-24 00:09 UTC
### Source information

The blank scanlation 1.4.39

### Source language

English

### Steps to reproduce

I go to the website try to click on a manga only to find out that it is updating but it falsely says site is erased but it's still up
![Screenshot_20241223_190456](https://github.com/user-attachments/assets/b994c5cd-f4aa-4453-b6bd-827d533e6b8b)

### Expected behavior

What should happen is me being able to access the chapters but I cant

### Actual behavior

I can't access the chapters and this is what it says 
![Screenshot_20241223_190602](https://github.com/user-attachments/assets/bf98284e-fe32-4c79-82c5-2a26653d97b8)

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 14

### Other details

![Screenshot_20241223_190750](https://github.com/user-attachments/assets/378dfa6b-cd34-4b00-af98-355304b39982)
As you can see the site is still up
https://theblank.net/
Link to the website above

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-24 01:01
Duplicate of #6648, it's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned by Smol-Ame** 2024-12-24 01:01 UTC
Labels: Bug, Duplicate

**Comment by demon456blade** [comment] 2024-12-24 01:51
Indeed I did not but as I looked at it now ,it still does not have a solution so what now?

**Comment by Smol-Ame** [comment] 2024-12-24 02:45
It means to shut up, wait for a fix to close the issue. Migrate to a different source if you can't wait, fix the extension yourself, or find somewhere that'll fix things on demand for you. Don't unnecessarily comment bump in the existing issue.
