### ISSUE TITLE
Manwa.me cannot load pictures 

### ISSUE THREAD

**Issue by salamander7456** [keiyoushi/tachiyomi-extensions-source#5346] opened 2024-10-03 20:23 UTC
### Source information

1.4.7

### Source language

Chinese 

### Steps to reproduce

1. When click the chapter in app, it load for some seconds then not work without any notice.
2. But the WebView was work
3. Changing sources in extensions is no help 
4. Changing user agent string is no help 
5. Clearing cookies abd WebView data is no help 

https://github.com/user-attachments/assets/e3b108d7-bef7-4edf-8bd7-405a37c2dd33

### Expected behavior

The chapter can be opened 

### Actual behavior

The chapter cannot load without notice 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-03 20:28
Duplicate of #5341

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

**Comment by salamander7456** [comment] 2024-10-03 20:37
> Duplicate of #5341
> 
> Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

In fact, this problem has been going on for almost a month. I saw an issue mentioning it before(Now closed). In that issue, developer said it will be fixed in the next version.This has indeed improved in the updated version 1.4.7. But now it has reappeared.

**Comment by salamander7456** [comment] 2024-10-03 20:42
> Duplicate of #5341
> 
> Search the existing issues first before opening a new one, and acknowledging that you did when you didn't

Sorry I noticed that earlier Chinese issue talk about it. It looks similar to my issue. Thank you for your reply, please delete this to avoid repeating.

**Comment by Smol-Ame** [comment] 2024-10-03 23:20
> In fact, this problem has been going on for almost a month. I saw an issue mentioning it before(Now closed). In that issue, developer said it will be fixed in the next version.This has indeed improved in the updated version 1.4.7. But now it has reappeared.

Source can change things to intentionally break the extension, it won't work forever & no guarantee for a fix in general, just have to wait.

Mark this issue as closed since it's a duplicate

**Closed as not planned** 2024-10-05 00:20 UTC
Labels: Bug, Duplicate
