### ISSUE TITLE
Add Zaimanhua

### ISSUE THREAD

**Issue by hsiayuchih** [keiyoushi/tachiyomi-extensions-source#5046] opened 2024-09-14 03:23 UTC
### Source name

Zaimanhua（再漫画）

### Source link

https://www.zaimanhua.com/

### Source language

Chinese

### Other details

Due to special reasons, the editors/uploaders of the original dmzj are all gone, the original manga site is no longer updated, and they have opened a new site of their own: zaimhua.

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-14 03:35
Duplicate of #5015

**Closed as not planned** 2024-09-14 04:44 UTC
Labels: Source request
