### ISSUE TITLE
Manga Demon

### ISSUE THREAD

**Issue by ReportIssueOnly** [keiyoushi/tachiyomi-extensions-source#4846] opened 2024-08-30 08:16 UTC
### Source information

Manga Demon

### Source language

English

### Source new URL

https://manga demon.org

### Other details

Fix extension old domain BUT webview new domain
![IMG_20240830_083609](https://github.com/user-attachments/assets/7937e861-0c62-42b8-a9dd-303bf725893e)
![IMG_20240830_083556](https://github.com/user-attachments/assets/c0613fd3-a189-4df8-b8b6-c784584eb326)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-30 08:18
Duplicate of #4770 

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

Also that's not the right URL, even compared to your own screenshot of the redirected page in WebView

**Comment by ReportIssueOnly** [comment] 2024-08-30 08:21
> Duplicate of #4770
> 
> Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.
> 
> Also that's not the right URL, even compared to your own screenshot of the redirected page in WebView

Then fix it rather than you yapping

**Comment by Smol-Ame** [comment] 2024-08-30 08:25
Damn, moody one aren't you.

There's already a proposed fix from another contributor, it's pending review & merge to the repo. Contributors are all volunteering their free time to provide fixes/new extensions. I've contributed a few quick fixes to give back to the community/repo, don't whine if you don't understand.

**Comment by AwkwardPeak7** [comment] 2024-08-30 08:29
> Then fix it rather than you yapping

Let me refund you the 0 dollars you paid us

**Closed as not planned by AwkwardPeak7** 2024-08-30 08:29 UTC
Labels: Bug, Duplicate, Domain changed
