### ISSUE TITLE
Chapter not found 

### ISSUE THREAD

**Issue by Tadaningenda** [keiyoushi/tachiyomi-extensions-source#4048] opened 2024-07-16 13:12 UTC
### Source information

MangaSwat 1.4.49

### Source language

Arabic

### Steps to reproduce

Add manga to category 
Showing chapters
Click to chapter 
Said:Chapter not found 

### Expected behavior

Show chapter perfectly 

### Actual behavior

If i go to wep view it send me to main page

### Mihon/Tachiyomi version

App version: 0.16.4.3-7714 (standard, 525c4715e, 125, 2024-07-11T13:25:14Z) Android version: 10 (SDK 29; build STK-L21VHN 10.0.0.233(C185E2R4P1)) Android build ID: STK-L21VHN 10.0.0.233(C185E2R4P1) Device brand: HONOR Device manufacturer: HUAWEI Device name: HWSTK-HF (STK-L21VHN) Device model: STK-LX1 WebView: Android System WebView 126.0.6478.134 MPV version: 4d32db2 Libplacebo version: v7.349.0 FFmpeg version: n7.0

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-07-16 14:17
Duplicate of #4045

you can change the URL in extension settings

**Closed as not planned** 2024-07-16 14:18 UTC
Labels: Bug, Duplicate

**Comment by Tadaningenda** [comment] 2024-07-16 14:58
> Duplicate of #4045
> 
> you can change the URL in extension settings

I did and still says chapter not found
