### ISSUE TITLE
Cloudflare error (not registering in app)

### ISSUE THREAD

**Issue by Morse069** [keiyoushi/tachiyomi-extensions-source#1535] opened 2024-02-25 09:05 UTC
### Source information

Temple Scan 1.4.37

### Source language

English

### Steps to reproduce

Open webview
Solve captcha
Sucess in captcha (can view the site in webview)
Cloudflare error in app

### Expected behavior

Can view manga entries in the app

### Actual behavior

![IMG_20240225_170300](https://github.com/keiyoushi/extensions-source/assets/121346796/8dfec020-c468-41d4-b1b8-bf59cea7abc1)
![IMG_20240225_170254](https://github.com/keiyoushi/extensions-source/assets/121346796/a935d84d-e0d3-4343-b92c-384ac460002f)

### Mihon/Tachiyomi version

0.16.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2024-02-25 10:23
Duplicate of #976

**Closed as not planned by stevenyomi** 2024-02-25 10:23 UTC
Labels: Bug, Duplicate, Cloudflare protected
