### ISSUE TITLE
They changed the URL of the Sussy Scans extension

### ISSUE THREAD

**Issue by ghost** [keiyoushi/tachiyomi-extensions-source#6830] opened 2024-12-27 08:29 UTC
### Source information

Sussy Scan 1.4.41

### Source language

pt-BR

### Source new URL

https://oldi.sussytoons.site/

### Other details

![IMG_2042](https://github.com/user-attachments/assets/56f3bac6-f9fe-49fc-b441-763641822003)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dreezf** [comment] 2024-12-27 08:50
New source URL is https://new.sussytoons.site/

**Comment by Smol-Ame** [comment] 2024-12-27 08:54
Duplicate of #6034, it's already reported before. Search the existing issues before opening a new one, and acknowledging that you did when you clearly didn't.

That's their old URL which the extension already uses.

**Closed as not planned by Smol-Ame** 2024-12-27 08:54 UTC
Labels: Bug, Duplicate, Domain changed
