### ISSUE TITLE
Kewn's Chapters; No Pages Found

### ISSUE THREAD

**Issue by Lapsen-Mirror** [keiyoushi/tachiyomi-extensions-source#4896] opened 2024-09-03 05:23 UTC
### Source information

Kewn Scans 1.4.6 

### Source language

English

### Steps to reproduce

1. Open any of Kewn's manhwas
2. Tap any chapter.
3. 'No Pages Found' will show.
![Screenshot_20240903_122349_Tachiyomi](https://github.com/user-attachments/assets/cc3c953f-cc2f-4f30-b497-08bf106b8fd0)

### Expected behavior

The chapter should appear.

### Actual behavior

No matter which chapter it is from Kewn, no chapter was able to load.

### Mihon/Tachiyomi version

0.14.7

### Android version

Android 13

### Other details

The WebView seems to be working fine with the chapters loading. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-03 05:25
1) Duplicate of #4869
2) If you wrote the right app version, ~~there's no way you're using our extensions since Tachiyomi 0.15.# is when the app allowed third-party extensions/repos~~
> I've been advised that you can use externally downloaded extensions in pre-0.15.# versions. But fact of the matter, besides duplicate issue, is that you should consider the following:
3) Tachiyomi is dead, switch to Mihon if you can

**Closed as not planned** 2024-09-03 05:52 UTC
Labels: Bug
