### ISSUE TITLE
Roumanwu:Unable to search

### ISSUE THREAD

**Issue by TangBaoY** [keiyoushi/tachiyomi-extensions-source#1824] opened 2024-03-11 21:51 UTC
### Source information

roumanwu 1.4.7

### Source language

Chinese

### Steps to reproduce

![Screenshot_2024-03-12-05-45-46-78_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/113247009/1efb7418-b491-41ab-9cb5-768c89fd5263)
![Screenshot_2024-03-12-05-46-02-16_76d0f6352040d5ab219b0498c33ac39d](https://github.com/keiyoushi/extensions-source/assets/113247009/9519b1d2-b6f6-44f7-8a77-903a6be0b07b)

### Expected behavior

Search successful

### Actual behavior

no result

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TangBaoY** [comment] 2024-03-13 07:10
find a way to
update the URL to restore it
Original
![Screenshot_2024-03-13-15-02-57-71_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/keiyoushi/extensions-source/assets/113247009/b26be977-5be7-4b46-91d8-257250023146)

After modification
![Screenshot_2024-03-13-15-01-59-66_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/keiyoushi/extensions-source/assets/113247009/073da2e1-0b8c-45c3-a1ed-8caa184d2645)

![Screenshot_2024-03-13-15-04-41-99_76d0f6352040d5ab219b0498c33ac39d.jpg](https://github.com/keiyoushi/extensions-source/assets/113247009/88846fa9-1fe3-4d2c-b8f2-839a2784d810)

**Comment by NeKoOuO** [comment] 2024-03-13 11:44
Have you encountered a situation where you cannot load images in the app and 401 is displayed, but the webview can still be used normally?

**Comment by stevenyomi** [comment] 2024-03-13 17:23
Duplicate of #1676

**Closed as not planned by stevenyomi** 2024-03-13 17:23 UTC
Labels: Bug, Duplicate

**Comment by TangBaoY** [comment] 2024-03-13 22:18
> Have you encountered a situation where you cannot load images in the app and 401 is displayed, but the webview can still be used normally?

As above, update the URL and it will return to normal.
