### ISSUE TITLE
Mangalionz:manga gives error 404 but in webview it works 

### ISSUE THREAD

**Issue by Deathmatters** [keiyoushi/tachiyomi-extensions-source#5746] opened 2024-10-28 19:56 UTC
### Source information

Mangalionz 1.4.40

### Source language

Arabic

### Steps to reproduce

I opened the extension 
I closed a manhwa
It didn't works 

### Expected behavior

I should enter to read a manhwa and find chapters existing 

### Actual behavior

When I enter to read a manga no chapter shows and it gives me an error 404

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

It's not an irl problem or an app problem and it been giving the same problem for 6 months

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-28 19:59
Duplicate of #5732

Wait for a fix or migrate to a different source, don't make multiple issue requests of the same issue

**Closed as not planned by Smol-Ame** 2024-10-28 19:59 UTC
Labels: Bug
