### ISSUE TITLE
slimeread não está foncionado está aparecendo códigos na parte da website

### ISSUE THREAD

**Issue by hendrickms** [keiyoushi/tachiyomi-extensions-source#6711] opened 2024-12-20 11:51 UTC
### Source information

Slimeread 1.4.15

### Source language

Português Brasil - PT-BR

### Steps to reproduce

Se vc entrar no slimeread aparecera a url está errada e quando entrar na website aparece esses código mesmo com o site de origem pegando
![Screenshot_20241220-084354](https://github.com/user-attachments/assets/780faa1f-f252-42a1-845a-d3c8a480ccb1)

### Expected behavior

Eu esperava que funcionasse tudo certo ou ao menos não desse esse erros de código qual nos outros como esse
![Screenshot_20241220-084637](https://github.com/user-attachments/assets/24e997b7-6301-4614-9a07-a8a10e30e944)

### Actual behavior

Mas ao inves disso aparece isso e a url parece estar certa 
![Screenshot_20241220-084642~2](https://github.com/user-attachments/assets/094be180-bc22-4723-9dec-424adb843cf9)
![Screenshot_20241220-084704](https://github.com/user-attachments/assets/9747f159-f4f2-4ea6-958c-74d5564e67d8)

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment] 2024-12-20 11:59
Duplicate of #6673

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed as not planned** 2024-12-20 11:59 UTC
Labels: Bug, Duplicate

**Comment by hendrickms** [comment] 2024-12-20 12:09
Desculpa por isso n farei novamente eu tava seguindo o que um video do Youtube falava e ainda fiz errado e vor ler resposta certa

**Comment by davisaid777** [comment] 2024-12-20 23:18
TA COM ERRO NO API URL DO "SLIMERED"
