### ISSUE TITLE
Japscan (FR) don't work

### ISSUE THREAD

**Issue by ElCacciatore** [keiyoushi/tachiyomi-extensions-source#5417] opened 2024-10-07 20:34 UTC
### Source information

Japscan 1.4.48

### Source language

French

### Steps to reproduce

Source don't work.
Site with webviewer work. Not in app. 

### Expected behavior

Like other sources. 

### Actual behavior

Not work anymore

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-07 20:46
Closing as a duplicate of #3629

This barebones issue report doesn't provide any information on what doesn't work. Be more descriptive & provide more details for future issue reports.

From my testing, the source has a high Cloudflare protection level, and you need to pass Cloudflare verification on every page (manga list, manga entry, chapters) for things to load up, but it can't grab the images (see issue mentioned above).

The homepage itself doesn't have/need Cloudflare verification, but always click around (or for future issues, check the manga pages/chapter itself) to see if there's extra verification/issues.

**Closed as not planned by Smol-Ame** 2024-10-07 20:46 UTC
Labels: Bug
