### ISSUE TITLE
https://www.hijala.com

### ISSUE THREAD

**Issue by anas7ye** [keiyoushi/tachiyomi-extensions-source#1827] opened 2024-03-11 22:52 UTC
### Source information

Hijala 

### Source language

Arabic 

### Steps to reproduce

NullPointerExcePtion:null
I can't download chapters due to NullPointerExcePtion:null problem I can't read chapters due to NullPointerExcePtion:null problem 

### Expected behavior

NullPointerExcePtion:null

### Actual behavior

NullPointerExcePtion:null

### Mihon/Tachiyomi version

1.10.5

### Android version

12

### Other details

![Screenshot_2024-03-11-22-20-00-540_eu kanade tachiyomi sy](https://github.com/keiyoushi/extensions-source/assets/152851438/ef615176-e90d-4226-9931-49108ea189b6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-03-11 23:06
Duplicate of #1812

**Closed as not planned by AwkwardPeak7** 2024-03-11 23:06 UTC
Labels: Bug
