### ISSUE TITLE
Galaxy Manga HTTP 404

### ISSUE THREAD

**Issue by a7mad115** [keiyoushi/tachiyomi-extensions-source#2023] opened 2024-03-21 13:31 UTC
### Source information

Galaxy Manga 1.4.31

### Source language

Arabic

### Steps to reproduce

 any time try to use the extension.

<img width="380" alt="Screenshot 2024-03-21 152244" src="https://github.com/keiyoushi/extensions-source/assets/66521428/18b2143e-70bb-4de1-a81e-43aaa6d60246">

### Expected behavior

the website change its structure made the problems.

### Actual behavior

<img width="380" alt="Screenshot 2024-03-21 152244" src="https://github.com/keiyoushi/extensions-source/assets/66521428/5711b052-7d44-46e1-87b7-cbc026f59915">

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2024-03-21 13:41
Duplicate of #1923

**Closed as not planned by AwkwardPeak7** 2024-03-21 13:41 UTC
Labels: Bug, Duplicate
