### ISSUE TITLE
Manga Cross

### ISSUE THREAD

**Issue by Millkay** [keiyoushi/tachiyomi-extensions-source#5433] opened 2024-10-08 10:58 UTC
### Source information

Manga Cross 1.4.5

### Source language

Japanese

### Steps to reproduce

After startup, nothing shows up

### Expected behavior

![Screenshot_2024-10-08-13-38-18-301_app mihon](https://github.com/user-attachments/assets/12bd51f7-7bd9-4882-bbb6-745370052f1d)

It was supposed to be something like this

### Actual behavior

![Screenshot_2024-10-08-13-56-19-381_app mihon](https://github.com/user-attachments/assets/4a1ecdc7-c5ea-4e17-a844-f014e90e0a9d)

And in reality, it's like this

### Mihon/Tachiyomi version

0.16.5

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-08 11:01
Duplicate of #2532

**Closed as not planned** 2024-10-08 11:01 UTC
Labels: Bug
